- source/OctopusTools/Commands/ImportCommand.cs
Minor cosmetic change to fix the label used for the command-specific options on the "import" command.
> Fix typo in import command options group name

- source/OctopusTools/Commands/ApiCommand.cs
- source/OctopusTools/Commands/CreateEnvironmentCommand.cs
- source/OctopusTools/Commands/CreateReleaseCommand.cs
- source/OctopusTools/Commands/DeleteReleasesCommand.cs
- source/OctopusTools/Commands/DeployReleaseCommand.cs
- source/OctopusTools/Commands/PromoteReleaseCommand.cs
- source/OctopusTools/Exporters/ProjectExporter.cs
- source/OctopusTools/Exporters/ReleaseExporter.cs
- source/OctopusTools/Infrastructure/CouldNotFindException.cs
- source/OctopusTools/OctopusTools.csproj
Fixed OctopusDeploy/Issues#1506
Sometimes users use the wrong API key with Octo.exe, and can't find projects or environments because the user they are running as doesn't have permission to see them.
After connecting, print the username we connected as
When we can't find a project/environment/etc., in the error message, suggest it might possibly be a permissions issue
Release note: Octo.exe reports authenticated user and has more helpful error messages
> Octo.exe displays username that owns API key and suggests permissions issues

- source/OctopusTools.Tests/Commands/DeployReleaseCommandTestFixture.cs
- source/OctopusTools.Tests/OctopusTools.Tests.csproj
- source/OctopusTools/Commands/DeploymentCommandBase.cs
We found that the --deploymenttimeout parameter had a bit of a misleading help text, which @Dalmirog updated in #62, based on the [conversation](http://help.octopusdeploy.com/discussions/questions/6140-deploymenttimeout-failing-teamcity-build-but-not-cancelling-octopus-deployment) we had on help.octopusdeploy.com.
We expected that the deployment timeout should cancel the build in octopus, which it did not. This pull request adds a new flag to octo.exe that cancels the deployment(s) if the timeout is reached.
> Add flag to enable cancellation of the deployment when timeout is reached

- source/OctopusTools/DUMMY.txt
- source/OctopusTools/OctopusTools.csproj
- source/OctopusTools/OctopusTools.nuspec
- source/OctopusTools/init.ps1
- tools/Build.proj
This is a potential ​*breaking change*​ with the NuGet package we publish to NuGet.org which is to move `octo.exe` into the `tools` folder. This means we don’t need to `DUMMY.txt` hack to make it install (current process), and `octo.exe` will be added to the `$env:PATH` so you can run `octo.exe` commands directly from the ​*PowerShell Manager Console*​.
> Move octo.exe into Tools Folder

- source/OctopusTools.Tests/Commands/ApiCommandFixture.cs
- source/OctopusTools.Tests/Commands/ApiCommandFixtureBase.cs
- source/OctopusTools.Tests/Commands/CreateReleaseCommandFixture.cs
- source/OctopusTools.Tests/Commands/DeployReleaseCommandTestFixture.cs
- source/OctopusTools.Tests/Commands/DummyApiCommand.cs
- source/OctopusTools.Tests/Commands/ListEnvironmentsCommandFixture.cs
- source/OctopusTools.Tests/Commands/ListProjectsCommandFixture.cs
- source/OctopusTools.Tests/Commands/ListReleasesCommandFixture.cs
- source/OctopusTools.Tests/Commands/Resources/CreateRelease.config.txt
- source/OctopusTools.Tests/OctopusTools.Tests.csproj
- source/OctopusTools/Commands/ApiCommand.cs
- source/OctopusTools/Commands/CreateEnvironmentCommand.cs
- source/OctopusTools/Commands/CreateProjectCommand.cs
- source/OctopusTools/Commands/CreateReleaseCommand.cs
- source/OctopusTools/Commands/DeleteReleasesCommand.cs
- source/OctopusTools/Commands/DeployReleaseCommand.cs
- source/OctopusTools/Commands/DeploymentCommandBase.cs
- source/OctopusTools/Commands/DumpDeploymentsCommand.cs
- source/OctopusTools/Commands/ExportCommand.cs
- source/OctopusTools/Commands/ImportCommand.cs
- source/OctopusTools/Commands/ListEnvironmentsCommand.cs
- source/OctopusTools/Commands/ListLatestDeploymentsCommand.cs
- source/OctopusTools/Commands/ListProjectsCommand.cs
- source/OctopusTools/Commands/ListReleasesCommand.cs
- source/OctopusTools/Commands/PromoteReleaseCommand.cs
Did a refactor using `IOctopusFileSystem` instead of `File` so it's a noisy PR.
The important parts are `CreateReleaseCommandFixture.cs` and `CreateRelease.config.txt` which test that parameters can be loaded from a file.
The implementation change is `ApiCommand.cs` line 173 that uses `optionsGroup` instead of just `options`.
> Load additional parameters from a file when --configfile is passed

- source/OctopusTools.Tests/Commands/Class1.cs
- source/OctopusTools.Tests/Commands/CleanEnvironmentCommandFixture.cs
- source/OctopusTools.Tests/OctopusTools.Tests.csproj
- source/OctopusTools/Commands/CleanEnvironmentCommand.cs
- source/OctopusTools/OctopusTools.csproj
New clean-environment Command will remove any machines from an environment which match a specified Status.  The command accepts the following parameters:
--environment="environment name"
--status=Offline
> Add clean-machines Command

- source/Octopus.Cli/Program.cs
Adds support for TLS protocols for Octo.exe to communicate with TLS-only installations of Octopus Server.
Fixes OctopusDeploy/Issues#2414
> Fix for Octo.exe to support TLS protocols

- NuGet.config
- source/Octopus.Cli/Commands/ImportCommand.cs
- source/Octopus.Cli/Exporters/ProjectExporter.cs
- source/Octopus.Cli/Importers/ProjectImporter.cs
- source/Octopus.Cli/Octopus.Cli.csproj
- source/Octopus.Cli/Util/FeedCustomExpressionHelper.cs
- source/Octopus.Cli/Util/FeedResourceCustomExpressionHelper.cs
Fix to allow custom expressions in Nuget feeds for projects.
The exporter and importer were attempting to verify all feeds against the API, but there are times when the project has custom expressions for the feed ids using Octostache variables. So this fix makes sure we only check feeds against the API if they are _real_ DB records, and not a custom expression feed.
Fixes OctopusDeploy/Issues#2432
> Bug custom expression feed

- source/Octopus.Cli.Tests/Commands/CreateChannelCommandFixture.cs
- source/Octopus.Cli.Tests/Octopus.Cli.Tests.csproj
- source/Octopus.Cli/Commands/CreateChannelCommand.cs
- source/Octopus.Cli/Octopus.Cli.csproj
The rationale behind this feature is to allow branch builds from TeamCity or other build servers to have a per-branch channel created for them.
`octo.exe create-channel --server=XYZ --apiKey=API-XYZ --channel="My New Channel" --project="My Project" --lifecycle=Default --update-if-exists`
Use case: a team using short-lived feature branches wants to create a different IIS binding for each branch. The current best solution appears to be to parse a release version number or a package name and extract a branch name into an output variable.
This solution would allow a much cleaner creation of a channel for any given branch. I discussed this with @michaelnoonan a while ago and offered to send a pull request if the Octopus team didn't get around to building it first. Here it is :)
This is a …
> Add "create-channel" command.

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.approved.txt
- source/Octopus.Client/Repositories/IUserRolesRepository.cs
I'm extending https://github.com/Suremaker/OctopusProjectBuilder to support user roles and teams, and I'm currently having to drop down to the client for create and modification.
I'd like to be able to do these operations through the repository instead.
The only role that can't be modified is the built-in system administrator role, this is handled by the API.
I've added signatures to public surface area test, however it's failing on master head relating to subscriptions.
> Add create and modify behavior to user roles repository

- source/Octo/Commands/ListLatestDeploymentsCommand.cs
The `list-latestDeployments` will show the latest deployment for each environment/project/tenant.
```
Handshaking with Octopus server: http://localhost:8065
Handshake successful. Octopus version: 0.0.0-local; API version: 3.0.0
Authenticated as: admin <null>
Loading projects...
Loading environments...
Loading dashboard...
Loading deployments...
- Project: A multi tenant project
- Environment: Production
Date: 24/11/2016 12:52:30 PM +10:00
Duration: 2 seconds
State: Success
Version: 0.0.5
Assembled: 24/11/2016 12:52:25 PM +10:00
Package Versions:
Release Notes:
- Project: A multi tenant project
- Environment: Production
- Tenant: Mo the Brewer
Date: 24/11/2016 12:26:22 PM +10:00
Duration: 2 seconds
State: Success
Version: 0.0.1
Assembled: 24/11/2016 12:25:52 PM +10:00
Package Versions: …
```
> Fix list-latestDeployments

- source/Octopus.Client/OctopusRepository.cs
- source/Octopus.Client/Repositories/Async/ProjectGroupRepository.cs
The Link that is called on the projectGroupResource does not eixist.
The actual link it should be pulling is Projects.
This is directly pulled from the API in 3.6.0
``` JSON
{
"Id": "ProjectGroups-1",
"Name": "Active Clients",
"Description": "Active clients.",
"EnvironmentIds": [],
"RetentionPolicyId": null,
"Links": {
"Self": "/api/projectgroups/ProjectGroups-1",
"Projects": "/api/projectgroups/ProjectGroups-1/projects"
}
}  
```
> Correction for Gathering ProjectGroup Projects

- source/Octo/Commands/CreateReleaseCommand.cs
- source/Octo/Commands/PackCommand.cs
- source/Octo/Util/StringExtensions.cs
If you pass a filepath to Octo.exe with a trailing backslash, it is easy to forget to escape it properly. Try to detect that and show a warning.
See also https://github.com/OctopusDeploy/OctoTFS/pull/74
Closes OctopusDeploy/Issues#2663
> Detect illegal path characters in folder arguments

- source/Octo.Tests/Commands/PackageVersionResolverFixture.cs
- source/Octo.Tests/Util/FakeOctopusFileSystem.cs
- source/Octo/Commands/PackageVersionResolver.cs
Resolves https://github.com/OctopusDeploy/Issues/issues/3148
In the server we support `<id>-<version>.zip` as well as `<id>.<version>.zip` in different places, but not at the same time. Need to check which is right (or both).
> Add zip version parsing to release creation process

- source/Octopus.Client/Repositories/Async/CertificateConfigurationRepository.cs
- source/Octopus.Client/Repositories/CertificateConfigurationRepository.cs
Registering a 3.11 polling-tentacle against a pre-3.11 server would fail without this change, as the "CertificateConfiguration" link didn't exist on the RootResource.
> Backwards compatibility change for certificates

- build.cake
- source/Octo/Commands/TaskOutputProgressPrinter.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client.Tests/Repositories/Async/TaskRepositoryTests.cs
- source/Octopus.Client/Model/TaskDetailsResource.cs
When we changed `TaskDetails.ActivityLog` to `ActivityLogs` (3.4.0ish) we no longer checked the progress of the children (ie each steps). Instead only checked the overall process. Therefore the log was only printed once the whole task has finished instead of when each step finished.
Tested on Latest server and 3.2.2.
Fixes #131
> Fixed the reporting of progress when using the deploy-release command

- source/Octopus.Client.Tests/Integration/OctopusClient/AntiforgeryTokenTests.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ApiConstants.cs
- source/Octopus.Client/OctopusAsyncClient.cs
- source/Octopus.Client/OctopusClient.cs
Based on this recommendation: https://en.wikipedia.org/wiki/Cross-site_request_forgery#Cookie-to-Header_Token
See related Octopus PR: https://github.com/OctopusDeploy/OctopusDeploy/pull/847
> If there is an anti-forgery cookie in the response, copy its value to the correct header for any outbound requests
> Customers will only need a newer Client version if they upgrade their Octopus Server and are using Username Password credentials
1. Customers using API Keys will not be affected - API Key authenticated requests are not subject to anti-forgery token validation.
2. Older servers don't send the anti-forgery cookie so it can't/won't be copied to any outgoing requests
3. Newer servers will require anti-forgery header if the client uses an auth cookie session, and will make recommendations …
> Add support for anti-forgery token using cookie-to-header pattern

- source/Octo/Commands/PackageVersionResolver.cs
octo.exe --packagesfolder is not currently recognizing nuget packages. Adding an asterisk to allow packages to be recognized.
> Fixed PackagesFolder not finding .nupkg files

- source/Octopus.Client.Tests/Integration/HttpIntegrationTestBase.cs
- source/Octopus.Client.Tests/Integration/OctopusClient/AntiforgeryTokenTests.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/RootResource.cs
- source/Octopus.Client/OctopusAsyncClient.cs
- source/Octopus.Client/OctopusClient.cs
In the rare-ish case where customers have multiple Octopus installations on the same domain (it does happen, quite a lot in our test environments too) we will end up with multiple cookies in the CookieCollection for that domain, and we were looking for the first match based on the common prefix. Quite often this would end up with the wrong anti-forgery cookie for that installation and fail validation. We should use the InstallationId to partition and find the correct anti-forgery cookie.
This should be both backwards and forwards compatible. We haven't released any versions of Octopus Server with CSRF support yet, so there also shouldn't be any compatibility concerns there.
See related commit for Server and JS: https://github.com/OctopusDeploy/OctopusDeploy/pull/847/commits/67bc3f64f8e5ac1 …
> Isolate anti-forgery token by InstallationId

- source/Octo/Diagnostics/LogExtensions.cs
Support issue: http://help.octopusdeploy.com/discussions/problems/52637
> Improved the error message when the TFS markdown file can't be written

- BuildAssets/Octo
- can be called via symlinks from any location
- works in docker
- passes on the arguments
> Fix unix octo start script so that it

- source/Octo/Commands/IPackageBuilder.cs
- source/Octo/Commands/NuGetPackageBuilder.cs
- source/Octo/Commands/PackCommand.cs
- source/Octo/Commands/ZipPackageBuilder.cs
pack command takes --verbose, will log out more info to start with all
the files added to ZIP and NuPkg
Fixes: https://github.com/OctopusDeploy/Issues/issues/3171
Taks:
Will come later:
- VSTS extension supporting changes
- Team City extension supporting changes (java)
> pack: --verbose flag for files in package logging

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Repositories/Async/CertificateRepository.cs
- source/Octopus.Client/Repositories/CertificateRepository.cs
Added `GetOctopusCertificate` method to `CertificateRepository` to avoid breaking existing scripts and code
Connects to https://github.com/OctopusDeploy/Issues/issues/3427
> GetOctopusCertificate backwards-compatibility

- source/Octopus.Client/OctopusAsyncClient.cs
On mono `/path` will result in `file:///path` if ToString() is used.
Fixes OctopusDeploy/Issues#3474
> Use original path to get response location

- .gitattributes
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/EventNotificationSubscription.cs
- source/Octopus.Client/Repositories/Async/EventRepository.cs
- source/Octopus.Client/Repositories/EventRepository.cs
Also changed *.approved.* files in gitattributes from binary (which is a macro for -text -diff) to just -text. This means your git program will show diffs for them, which is pretty handy.
I added doc types to the end of the argument list, which I assume is the right way to go so we don't break things for people?
> Add document types to Events.List

- source/Octo.Tests/Commands/PackageVersionResolverFixture.cs
- source/Octo/Commands/IPackageVersionResolver.cs
- source/Octo/Commands/PackageVersionResolver.cs
- source/Octo/Commands/ReleasePlan.cs
The current --package argument handling doesn't work as described in https://octopus.com/docs/api-and-integration/octo.exe-command-line/creating-releases. 
Specifically, if you
- provide a default `--packageversion=1.1.1` argument
- do NOT  provide a `--package=stepname:1.2.3` argument 
- provide a `--package=my.package.id:1.2.3` argument
In this case the default will be preferred over the packageid override.
This fix changes the fallback to stepname -> packageid -> default.
> Fix for PackageId-based version overrides

- source/Octopus.Client/Repositories/Async/BasicRepository.cs
- source/Octopus.Client/Repositories/BasicRepository.cs
> Only added the `{ids}` parameter if it didn't already exist.

- source/Octopus.Client.Tests/Repositories/OctopusAsyncRepositoryTests.cs
- source/Octopus.Client/OctopusAsyncClient.cs
- source/Octopus.Client/Repositories/Async/CertificateConfigurationRepository.cs
The Repository needs to be initialized after establish session, which has to be done in the factory method (Create).
This means the user cannot create a client via OctopusAsyncClient ctor.
Fixed #178
> OctopusAsyncClient ctor initializes the Repository too early

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Repositories/Async/ProjectRepository.cs
- source/Octopus.Client/Repositories/ProjectRepository.cs
Project releases can now be searched via a version filter.  This is related to OctopusDeploy/Issues#3533
Tests:
- Updated existing tests only.  Adding API test in Octopus E2E Tests for better coverage.
> Added support to filter/search project releases

- source/Octopus.Client/Model/MachineScriptPolicy.cs
Causes tentacle registrations to throw with the error below. I also did a quick check against the Octopus.Core.Resources namespace and a search in this repo for 'public enum' but found no other missing values 😄 
> 
> INFO  Connected sucessfully
> INFO  Registering the tentacle with the server at https://octopusserver/
> ERROR  ===============================================================================
> FATAL  Unable to process response from server: Error converting value "OnlyConnectivity" to type 'Octopus.Client.Model.MachineScriptPolicyRunType'. Path 'Items[0].MachineHealthCheckPolicy.SshEndpointHealthCheckPolicy.RunType', line 18, position 39.. Response content: {
>   "ItemType": "MachinePolicy",
>
> Adding missing enum MachineScriptPolicyRunType.OnlyConnectivity

- source/Octopus.Client/Repositories/Async/ReleaseRepository.cs
This fixes a bug in the Releases async repository where it was not awaiting properly.
If you called this method with another call to deploy a release straight afterwards, there was a high risk the release would be deployed with the wrong variables snapshot (ie. octo.exe and the deploy-release command).
> Fixing release snapshot repository to await properly

- source/Octo/Commands/ApiCommand.cs
- source/Octo/Commands/ReleasePlan.cs
- source/Octo/Commands/ReleasePlanBuilder.cs
- source/Octo/Commands/ReleasePlanItem.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ReleaseTemplatePackage.cs
- source/Octopus.Client/Model/SelectedPackage.cs
As we're obsoleting a client facing property in `Octopus.Client`, I guess we should do a `major` version bump here or can we get away with a `minor` bump as the property is still available...
Related to OctopusDeploy/Issues#3424
> Renaming StepName property to ActionName

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/SmtpConfigurationResource.cs
The API for SMTP password configuration has been changed to use `SensitiveValue` to be more consistent with usage in other areas. The change is still backwards compatible however the new will still be honoured but will be dropped in 5.x.
> Deprecate NewSmtpPassword

- source/Octo/Importers/ProjectImporter.cs
Fixes OctopusDeploy/Issues#4037
If a project channel has a version rule, it will fail on import when using `Import` command from `Octo.exe`
Channel version rule requires a `Package Step`, however project importer imports the `Channels` before the `DeploymentProcess`, when Octopus Server try to save the Channel, it looks for the referenced `Package Step` which isn't imported yet and throw exception
Change the import order to save `DeploymentProcess` before `Channels`, then remap the new channel ids back to the newly imported actions
- Import a project with channel version rule which is not in the target server
Expect output: Project, Channels and Deployment process imported successfully
- Import a project with channel version rule which exists in the target server
Expect output: Project, …
> Fix Octo.exe project import problem if channel has version rule

- source/Octopus.Client.Tests/Conventions/ClientConventions.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Extensibility/Attributes/ApiPropertyAttribute.cs
- source/Octopus.Client/Extensibility/Attributes/WriteableAttribute.cs
- source/Octopus.Client/Extensibility/Extensions/Infrastructure/Configuration/ExtensionConfigurationResource.cs
- source/Octopus.Client/Extensibility/Href.cs
- source/Octopus.Client/Extensibility/IResource.cs
- source/Octopus.Client/Extensibility/LinkCollection.cs
- source/Octopus.Client/Octopus.Client.csproj
Moved everything that was in the Octopus.Client.Extensibility NuGet package back in to this library.
Was able to keep the same namespaces for all of the classes that moved, so consumers only need to drop the reference to the 2nd NuGet package. Or can go back to just grabbing the single Dll.
Tweaked the tests too, as the check for the resource objects all being in the Model namespace should only apply to the derived classes, not the IResource interface or abstract base classes.
> Remove extensibility package

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Repositories/Async/BasicRepository.cs
- source/Octopus.Client/Repositories/Async/ICreate.cs
- source/Octopus.Client/Repositories/BasicRepository.cs
- source/Octopus.Client/Repositories/ICreate.cs
In order to clone a project through the API you have to be able to pass `clone` as a Url parameter in the POST. The BasicRepository didn't have support for doing that.
Tested using LINQPad and the following
```
var octopusUrl = "http://localhost:8065";
var apiKey = "API-zzzzzzzzzzzzzzzzzzz";
var endpoint = new OctopusServerEndpoint(octopusUrl, apiKey);
var repository = new OctopusRepository(endpoint);
var project = new ProjectResource
{
Name = "Cloned Project",
Slug = "cloned-project",
ProjectGroupId = "ProjectGroups-z",
LifecycleId = "Lifecycles-zz"
};
repository.Projects.Create(project, new { clone = "Projects-zzz"});
```
> extra parameter to allow args to be passed in calls to Create

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/IOctopusAsyncRepository.cs
- source/Octopus.Client/IOctopusRepository.cs
- source/Octopus.Client/Model/Migrations/SpaceImportResource.cs
- source/Octopus.Client/Model/Migrations/SpacePartialExportResource.cs
- source/Octopus.Client/OctopusAsyncRepository.cs
- source/Octopus.Client/OctopusRepository.cs
- source/Octopus.Client/Repositories/Async/MigrationRepository.cs
- source/Octopus.Client/Repositories/MigrationRepository.cs
We want to start exposing the migration API for hosted, so it's time to start exposing this in OctopusClients.
I also sorted the properties in the main repositories, as this has been bugging my OCD :)
> Adding migration models and repositories

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Operations/IRegisterMachineOperation.cs
- source/Octopus.Client/Operations/RegisterMachineOperation.cs
So that you can specify how a Tentacle behaves with tenanted deployments at registration time (ie, during the `register-with` call).
Relates to: https://github.com/OctopusDeploy/Issues/issues/3782
> Add TenantedDeploymentParticipation param to RegisterMachineOperation

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/IOctopusAsyncRepository.cs
- source/Octopus.Client/IOctopusRepository.cs
- source/Octopus.Client/OctopusAsyncRepository.cs
- source/Octopus.Client/OctopusRepository.cs
- source/Octopus.Client/Repositories/Async/TenantVariablesRepository.cs
- source/Octopus.Client/Repositories/TenantVariablesRepository.cs
New repository to retrieve all tenant variables via the `/api/tenantvariables/all{?projectId}` endpoint.
Needed for the Hosted Portal project
> Add repository to retrieve all tenant variables

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/DiscoverMachineOptions.cs
- source/Octopus.Client/Repositories/Async/MachineRepository.cs
- source/Octopus.Client/Repositories/MachineRepository.cs
- tools/packages.config
Extra method added to avoid breaking API change, the Options object should ensure new parameters are easier to add. Fixes https://github.com/OctopusDeploy/OctopusClients/issues/244
> Added support for specifying the proxy on the Discover call

- source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs
Otherwise we get a null reference expception
> It looks like we should be using commandOutputProvider here

- source/Octo/Octo.csproj
Added portable RID for [linux](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#linux-rids) and [mac](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#macos-rids)
> Add netcore 2.0 portable rids for linux and mac

- BuildAssets/Octo.cmd
This fixes a problem when trying to use the batch file from another folder. It will complain about not being able to find Octo.dll otherwise.
> octo.cmd for portable fails if executed from another directory

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/IOctopusAsyncClient.cs
- source/Octopus.Client/IOctopusClient.cs
- source/Octopus.Client/OctopusAsyncClient.cs
- source/Octopus.Client/OctopusClient.cs
As we no longer have the route of `api/global/MixScopedThing`, post/put request should be based on the `SpaceId` inside the resource, `ForGlobalContext` is no longer needed. We can update this one and start changing codes in Octopus server project
> Spaces api update

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/OctopusServerNodeResource.cs
Transient nodes are not going to be a thing anymore.
This reverts commit 4d61eb4505ea1ceb8410d88ec7996a6152517a01.
> Revert "Add heartbeat policy to nodes"

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/SubscriptionResource.cs
Removes IncludeEventsFromSpaces - no longer considered necessary to support spaces.
Related to https://github.com/OctopusDeploy/OctopusDeploy/pull/2851
> Remove IncludeEventsFromSpaces

- source/Octopus.Client/OctopusClient.cs
I would not call it a supported feature but it might give some of our biggest clients time to migrate all of their Octopus Servers to Spaces without having to use different version of the client with different versions of the server.
> Make the client work with ALL THE SERVERS

- source/Octopus.Client/Editors/Async/ProjectEditor.cs
- source/Octopus.Client/Editors/ProjectEditor.cs
- source/Octopus.Client/Repositories/Async/ProjectRepository.cs
- source/Octopus.Client/Repositories/ProjectRepository.cs
Relates to: https://github.com/OctopusDeploy/Issues/issues/4960
Source https://help.octopus.com/t/octopus-client-4-41-2-breaking-change/21440
> Make new project cloneId optional to make it backwards compatible again

- source/Octopus.Cli/CliProgram.cs
- source/Octopus.Cli/Commands/ApiCommand.cs
- source/Octopus.Cli/Commands/Channel/CreateChannelCommand.cs
- source/Octopus.Cli/Commands/CommandBase.cs
- source/Octopus.Cli/Commands/Deployment/DeployReleaseCommand.cs
- source/Octopus.Cli/Commands/Deployment/DeploymentCommandBase.cs
- source/Octopus.Cli/Commands/Package/PushCommand.cs
- source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs
- source/Octopus.Cli/Commands/Releases/DeleteReleasesCommand.cs
- source/Octopus.Cli/Commands/VersionCommand.cs
- source/Octopus.Cli/Repositories/OctopusRepositoryCommonQueries.cs
- source/Octopus.Cli/Util/CommandOutputProvider.cs
- source/Octopus.Cli/Util/ICommandOutputProvider.cs
- source/Octopus.Client.Tests/Operations/RegisterMachineOperationFixture.cs
- source/Octopus.Client/IOctopusAsyncClient.cs
- source/Octopus.Client/IOctopusClient.cs
- source/Octopus.Client/Model/InterruptionResource.cs
- source/Octopus.Client/Model/TaskResource.cs
- source/Octopus.Client/OctopusAsyncClient.cs
- source/Octopus.Client/OctopusClient.cs
- source/Octopus.Client/OctopusRequest.cs
- source/Octopus.Client/OctopusResponse.cs
- source/Octopus.Client/OctopusServerEndpoint.cs
- source/Octopus.Client/Operations/IRegisterMachineOperationBase.cs
- source/Octopus.Client/Operations/RegisterMachineOperationBase.cs
Fixes a few small issues with command line help for octo.exe:
* Command specific (eg `octo.exe list-releases --help`) help shows `Or use octo help <command> for more details.`. The only problem is there that that shows the same help.
* `octo.exe version --help` doesn't show help 
* Some of the help text uses the incorrect casing for `Octopus Server`
* The `deploy-release` command's `--deployto` argument is missing missing `; specify this argument multiple times to deploy to multiple environments` which was added in the help docs.
Fixes https://github.com/OctopusDeploy/Issues/issues/5034
> Bug clihelp

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/IOctopusCommonAsyncRepository.cs
- source/Octopus.Client/IOctopusSpaceAsyncRepository.cs
- source/Octopus.Client/IOctopusSystemAsyncRepository.cs
- Need to be able to get the global octopus server certificates without stepping into a space scope
- You can't currently actually install community action templates into a non-default space, because the community action template repository is only exposed on the system repository.
> Spaces tweak repository scope

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ActionUpdateOutcome.cs
- source/Octopus.Client/Model/ActionUpdatePackageUsedBy.cs
- source/Octopus.Client/Model/ActionUpdateRemovedPackageUsage.cs
- source/Octopus.Client/Model/ActionUpdateResultResource.cs
- source/Octopus.Client/Repositories/Async/ActionTemplateRepository.cs
Added result when updating deployment actions from step templates to indicate a removed package was in use.
See https://github.com/OctopusDeploy/OctopusDeploy/pull/3113
> Report 'removed packages in use' when attempting to update deployment actions from templates

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/IOctopusAsyncClient.cs
- source/Octopus.Client/IOctopusClient.cs
- source/Octopus.Client/OctopusAsyncClient.cs
- source/Octopus.Client/OctopusClient.cs
Marking the old root document properties as obsolete to encourage people to avoid them.
Also prevent them from showing up in intellisense so new people won't even know about them.
> Re-added legacy root document properties and marked them as obsolete.

- build.cake
Fixes https://github.com/OctopusDeploy/Issues/issues/5175
Octodiff.exe needs to be repacked to enable delta transfers.
> Embedded octodiff into the windows exe

- BuildAssets/Octo
As suggested by John Smith via a Support Ticket.
Changes the line 
`LTTNG_UST_REGISTER_TIMEOUT=0 dotnet Octo.dll $*`
to
`LTTNG_UST_REGISTER_TIMEOUT=0 dotnet Octo.dll "$@"`
Tested locally. Fails with original line, and works as expected with the change. Nice little tweak.
> One small change in Linux Shell script to better support spaces in Project Names

- Dockerfiles/alpine/Dockerfile
Same fix as for our shell script ([PR](https://github.com/OctopusDeploy/OctopusClients/pull/376)) but for the `alpine` docker image
Fixes OctopusDeploy/Issues#4878
> Correctly escape args passed to octo in alpine docker image.

- source/Octopus.Cli/Commands/ApiCommand.cs
- source/Octopus.Cli/Util/SerilogLogProvider.cs
modified the SerilogLogProvider so it is aware of when message printing is being suppressed.
We may still want a more holistic longer term solution, but this addresses the immediate issues with the user agent logging interfering with the json output.
Fixes OctopusDeploy/Issues#5224
> Suppress logging when using json output

- source/Octopus.Cli/Commands/ApiCommand.cs
- source/Octopus.Client/AutomationEnvironments/AutomationEnvironmentProvider.cs
Fixes https://github.com/OctopusDeploy/Issues/issues/5292
I considered multiple ways of handling this while trying to stay true to serilogs structured logging principals... All of them were way more code and added more complexity.
As its unlikely we'll be shipping `octo.exe` output direct to seq or other structured logging endpoint, it's not a priority to support searching by message template (especially as we'd more likely just search for `authenticated as`).
> Dont output empty brackets if no email address

- source/Octopus.Client/Model/PropertyValueResource.cs
Using the operator correctly sets SensitiveValue.HasValue. Fixes #389
> Use operator when setting SensitiveValue

- build.cake
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/LeadershipRank.cs
- source/Octopus.Client/Model/OctopusServerClusterSummaryResource.cs
- source/Octopus.Client/Model/OctopusServerNodeResource.cs
- source/Octopus.Client/Model/OctopusServerNodeSummaryResource.cs
- source/Octopus.Client/Repositories/Async/OctopusServerNodeRepository.cs
- source/Octopus.Client/Repositories/OctopusServerNodeRepository.cs
- source/OctopusClients.sln
Client updates for https://github.com/OctopusDeploy/OctopusDeploy/pull/3391
**note: these are breaking changes**, but we (@michaelnoonan  and I) came to the conclusion that this would be low risk (as its unlikely that people are using the client for this) and that changing the `LastSeen` to a `DateTimeOffset` is worth the break.
> Enh splitnodetable

- source/Octopus.Cli/Commands/Deployment/DeploymentCommandBase.cs
This adds `--noDeployAfter` to `Octo.exe` which sets `QueueTimeExpiry` on the API, similar to `--deployAt` which sets `QueueTime`.
The original issue suggested the name `--dontStartAfter` but I thought `--noDeployAfter` sounded a little more idiomatic and consistent with the other option. Let me know if a better name springs to mind.
Fixes OctopusDeploy/Issues#5159.
> Add Octo.exe argument --noDeployAfter to set QueueTimeExpiry

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/MachineHealthCheckPolicy.cs
- source/Octopus.Client/Model/MachineScriptPolicy.cs
I'm not sure about the naming of `HealthCheckType` as a `HealthCheckType` already exists.
Would `MachinePolicyHealthCheckType` work better?
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/3724
This is a breaking change.
> Resource changes to reflect machine policy model changes

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Repositories/Async/ServerStatusRepository.cs
- source/Octopus.Client/Repositories/ServerStatusRepository.cs
Details: https://github.com/OctopusDeploy/OctopusDeploy/pull/3710
Technically speaking this is a breaking change but this C# API was introduced by me only a few weeks ago and I don't expect people to use it.
> Exposed server health status directly

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client.Tests/Serialization/MultiIsoDateTimeFormatConverterFixture.cs
- source/Octopus.Client/Model/PackageResource.cs
- source/Octopus.Client/Serialization/JsonSerialization.cs
- source/Octopus.Client/Serialization/MultiIsoDateTimeFormatConverter.cs
This change ensures that the `PackageResource` model matches what the Octopus server is now returning for the `PublishDate` which is a nullable DateTimeOffset.  Related server change https://github.com/OctopusDeploy/OctopusDeploy/pull/3937
For older clients reading the server, there is no real breaking change since they are just reading string. For new clients reading old servers,  the multi-deserialization logic provided in this PR will convert both new server or old server responses to a DateTimeOffset property.
> Support deserializing package publish date using multiple formats

- source/Octopus.Client/OctopusAsyncClient.cs
- source/Octopus.Client/OctopusClient.cs
Log request methods & URLs at trace level. Not visible by default, but useful sometimes.
> Log request methods & URLs at trace level

- source/Octopus.Client.Tests/Integration/OctopusClient/SslTests.cs
For whatever reason, my machines produce a slightly different exception than this test expectation.
A GitHub search doesn't show any code relying directly on the type or message, so I think allowing either is probably going to be okay.
This has been necessary on all 3 machines I have tried, including a clean install of Win10 Pro 1809 with minimal tools to run the tests (our traditional .NET Core SDK 2.1.300, .NET Framework SDK 4.5.2, Visual Studio command line tools, git).
> test adjustment: accept both kinds of certificate rejection exception

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/OverwriteMode.cs
- source/Octopus.Client/Repositories/Async/BuiltInPackageRepositoryRepository.cs
- source/Octopus.Client/Repositories/Async/PackageMetadataRepository.cs
- source/Octopus.Client/Repositories/BuiltInPackageRepositoryRepository.cs
- source/Octopus.Client/Repositories/PackageMetadataRepository.cs
Adding OverwriteMode, to replace the `replace` boolean in the push APIs. Adds the ability for the caller to IgnoreExisting.
Relates to OctopusDeploy/Octopus-TeamCity#18
> Overwrite mode

- source/Octopus.Client/Repositories/Async/BuiltInPackageRepositoryRepository.cs
- source/Octopus.Client/Repositories/BuiltInPackageRepositoryRepository.cs
Two `PushPackage` methods similar signatures and default parameters results in an ambiguous invocation when the parameter is not specified.
```
Task<PackageFromBuiltInFeedResource> PushPackage(string fileName, Stream contents, bool replaceExisting = false);
Task<PackageFromBuiltInFeedResource> PushPackage(string fileName, Stream contents, OverwriteMode overwriteMode = OverwriteMode.FailIfExists);
```
Calling `PushPackage(fileName, contents)` is ambiguous.
> Remove default value for `overwriteMode` parameter

- build.cake
- source/Octopus.Client.Tests/AutomationEnvironment/AutomationEnvironmentProviderFixture.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/AutomationEnvironments/AutomationEnvironmentProvider.cs
- source/Octopus.Client/Model/AutomationEnvironment.cs
- source/Octopus.Client/OctopusClientFactory.cs
- source/Octopus.Client/Properties/AssemblyInfo.cs
- source/Octopus.Client/Serialization/Serializer.cs
- source/Octopus.Client/Util/DynamicExtensions.cs
We historically had ilmerged newtonsoft.json into Octopus.Clients, but when the repo was split to move octo.exe into it's own repo, this ilmerge was removed.
As lots of our sample scripts (eg https://github.com/OctopusDeploy/OctopusDeploy-Api/blob/master/Octopus.Client/PowerShell/Projects/CreateProject.ps1) just go
```
Add-Type -Path 'Octopus.Client.dll' 
```
and dont highlight that we need to go 
```
Add-Type -Path 'NewtonSoft.Json.dll' 
```
as well, this has broken a bunch of use cases.
> ILMerge in newtonsoft.json

- source/Octopus.Client/Model/DeploymentResource.cs
- source/Octopus.Client/Model/EnvironmentResource.cs
There is misleading information in xmldoc for UseGuidedFailure filed  in EnvironmentResource and DeploymentResource. It says that behaviour can be overriden with Octopus.UseGuidedFailure variable, but according to https://github.com/OctopusDeploy/Issues/issues/3588 - this variable was removed in `3.0`
> Change xmldoc for UseGuidedFailure field

- source/Octopus.Client/Model/OverwriteMode.cs
- source/Octopus.Client/OctopusAsyncRepository.cs
- source/Octopus.Client/Repositories/Async/BuiltInPackageRepositoryRepository.cs
- source/Octopus.Client/Repositories/Async/PackageMetadataRepository.cs
- source/Octopus.Client/Repositories/BuiltInPackageRepositoryRepository.cs
- source/Octopus.Client/Repositories/PackageMetadataRepository.cs
Log a warning if `OverwriteMode.IgnoreIfExists` gets used when connected to an older version of server
Relates to OctopusDeploy/Octopus-TeamCity#18
> OverwriteMode warning when using older server

- source/Octopus.Client.Tests/Integration/OctopusClient/SslTests.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Exceptions/OperationNotSupportedByOctopusServerException.cs
- source/Octopus.Client/Model/PackageMetadata/OctopusPackageMetadata.cs
- source/Octopus.Client/OctopusAsyncClient.cs
- source/Octopus.Client/Repositories/Async/PackageMetadataRepository.cs
- source/Octopus.Client/Repositories/PackageMetadataRepository.cs
Throw a more meaningful exception if the server doesn't support pushing metadata.
Relates to OctopusDeploy/Octopus-TeamCity#31
> Push metadata error handling

- source/Octopus.Client.Tests/Conventions/ClientConventions.cs
- source/Octopus.Client.Tests/Conventions/RepositorySymmetryConventions.cs
- source/Octopus.Client.Tests/Integration/HttpIntegrationTestBase.cs
- source/Octopus.Client.Tests/Integration/OctopusClient/AntiforgeryTokenTests.cs
- source/Octopus.Client.Tests/Integration/OctopusClient/BuildServerHeadersBaseTests.cs
- source/Octopus.Client.Tests/Integration/OctopusClient/UserAgentTests.cs
- source/Octopus.Client.Tests/Integration/Repository/MachineRepositoryTest.cs
- source/Octopus.Client.Tests/Octopus.Client.Tests.csproj
- source/Octopus.Client.Tests/Repositories/OctopusRepositoryTests.cs
As we now ship a sync client for both net452 and netcore
Also remove `HAS BEST_CONVENTIONAL` as that is also available for netcore.
> Remove SYNC_CLIENT compile time constant

- build.cake
- source/Octopus.Client/Octopus.Client.nuspec
Because we were using raw `dotnet pack` to create the dll, it was assuming that all the dependencies from the project file should be used as dependencies of the nuget package. However, it didn't know that we'd already ILMerged the `newtonsoft.json` dependency in.
This PR modifies the nupkg so that it no longer lists these dependencies.
We also spotted that octodiff was not being inlined anymore, so this is now being inlined again.
Fixes https://github.com/OctopusDeploy/OctopusClients/issues/453
> ILMerge octodiff, and fix nupkg package to remove unneeded dependencies

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ActionTemplateParameterResource.cs
- source/Octopus.Client/Model/ControlType.cs
Needed for some tests in server - see https://github.com/OctopusDeploy/OctopusDeploy/pull/4400/files#diff-ff3d599cf4037ea089a39cf5a9320979R191
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/4400
Relates to OctopusDeploy/Issues#5835
> Add missing AmazonWebServicesAccount to ControlType

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/DeploymentPreviewResource.cs
- source/Octopus.Client/Model/DeploymentProcessResource.cs
- source/Octopus.Client/Model/DeploymentResource.cs
- source/Octopus.Client/Model/ProjectResource.cs
New fields to allow setting of a deployment changes template. This is used during the deployment creation to generate ChangesMarkdown, which is used to render in the portal and can be used from email templates etc.
Relates to OctopusDeploy/Issues#5604
> Deployment changes (notes)

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/DeploymentResource.cs
We store deployed by on a deployment, but we were making people jump through hoops to get it from the events endpoint.
Relates to https://github.com/OctopusDeploy/Issues/issues/5925
> Add deployedby to deployment resource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/IOctopusSpaceAsyncRepository.cs
- source/Octopus.Client/IOctopusSpaceRepository.cs
- source/Octopus.Client/Model/BuildInformation/ReleasePackageVersionBuildInformationResource.cs
- source/Octopus.Client/Model/DeploymentProcessResource.cs
- source/Octopus.Client/Model/DeploymentResource.cs
- source/Octopus.Client/Model/IExecutionResource.cs
- source/Octopus.Client/Model/IProcessResource.cs
- source/Octopus.Client/Model/ISnapshotResource.cs
- source/Octopus.Client/Model/ReleaseResource.cs
- source/Octopus.Client/Model/RunbookProcessResource.cs
- source/Octopus.Client/Model/RunbookRunResource.cs
- source/Octopus.Client/Model/RunbookSnapshotResource.cs
- source/Octopus.Client/OctopusAsyncRepository.cs
- source/Octopus.Client/OctopusRepository.cs
- source/Octopus.Client/Repositories/Async/RunbookProcessRepository.cs
- source/Octopus.Client/Repositories/RunbookProcessRepository.cs
In phase 1 of Runbooks, we never got around to fully refactoring Runbook-related resources to match the same inheritance as the Core.Model classes. This PR does this, so these's less danger of changing one and accidentally breaking the other.
> Refactoring Runbook-related resources

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ProcessReferenceDataItem.cs
- source/Octopus.Client/Model/ScopeField.cs
- source/Octopus.Client/Model/ScopeSpecification.cs
- source/Octopus.Client/Model/VariableScopeValues.cs
In the previous cycle for runbooks we did not deal with scoping variables to particular runbooks which prevented us from enabling prompted variables. This PR adds the client resource changes needed to support scoping variables to runbooks and deployment processes
> Update scope resource changes for runbook process scoping

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ProjectTriggerResource.cs
- source/Octopus.Client/Repositories/Async/ProjectTriggerRepository.cs
- source/Octopus.Client/Repositories/ProjectTriggerRepository.cs
Provide runbook ids to the method `FindByRunbook` and the result will be any project triggers matching those ids.
> Add project trigger filtering by runbook

- source/Octopus.Client.Tests/Integration/HttpIntegrationTestBase.cs
- source/Octopus.Client.Tests/Operations/RegisterMachineOperationFixture.cs
- source/Octopus.Client.Tests/Repositories/Async/BasicRepositoryFixture.cs
- source/Octopus.Client.Tests/Repositories/Async/TaskRepositoryTests.cs
- source/Octopus.Client.Tests/Repositories/OctopusAsyncRepositoryTests.cs
- source/Octopus.Client.Tests/Repositories/OctopusRepositoryTests.cs
- source/Octopus.Client.Tests/Spaces/MixedScopeSpaceContextExtensionTests.cs
- source/Octopus.Client.Tests/Spaces/SpaceIdAsyncTests.cs
- source/Octopus.Client/Repositories/Async/BasicRepository.cs
- source/Octopus.Client/Repositories/Async/ProjectTriggerRepository.cs
- source/Octopus.Client/Repositories/Async/ScopedUserRoleRepository.cs
- source/Octopus.Client/Repositories/Async/TeamsRepository.cs
- source/Octopus.Client/Repositories/Async/UserRolesRepository.cs
- source/Octopus.Client/Repositories/BasicRepository.cs
- source/Octopus.Client/Repositories/ProjectTriggerRepository.cs
- source/Octopus.Client/Repositories/ScopedUserRoleRepository.cs
- source/Octopus.Client/Repositories/TeamsRepository.cs
- source/Octopus.Client/Repositories/UserRolesRepository.cs
For the cases where we have decided we must make a breaking change in Server and Octopus.Client.
The client will have a resource that's no longer compatible with *old versions of server*. We want to alert/protect the customer in this scenario.
- We want this check to only happen at the time of calling specific API (method) on specific repositories (not at repository creation time).
- It may often impact the entire repository.
- This is the case with this most recent upcoming change.
- This is also the case with the historic  Team/ScopedUserRole/UserRole change made for 2019.1.0
Here is the start of this idea.
- Would be fine, as the `versionThreshold` would just be bumped up higher again.
Using client against:
1. Server 2019.10 no error
2. Server 2018.10 expected to see error
> Backwards Compat Check

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/Triggers/DeployLatestReleaseActionResource.cs
Working on Octopus Client changes for:
**Private link**
https://trello.com/c/64dGj9aQ/78-dont-re-deploy-release
Server changes at: https://github.com/OctopusDeploy/OctopusDeploy/pull/4748
> WIP - Client update to add ShouldRedeployWhenReleaseIsCurrent flag

- source/Octopus.Client.E2ETests/NuSpecDependenciesFixture.cs
- source/Octopus.Client.E2ETests/Octopus.Client.E2ETests.csproj
- source/Octopus.Client.E2ETests/TestHelpers.cs
- source/Octopus.Client.Tests/Octopus.Client.Tests.csproj
- source/Octopus.Client/Octopus.Client.csproj
This PR makes it possible to do basic development of this library in non-windows OSes like linux or macOS. Only the compatible target frameworks are compiled in those OSes.
> Improve development experience in non-windows environments

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/DaysOfWeek.cs
- source/Octopus.Client/Model/Triggers/ScheduledTriggers/ContinuousDailyScheduledTriggerFilterResource.cs
- source/Octopus.Client/Model/Triggers/ScheduledTriggers/OnceDailyScheduledTriggerFilterResource.cs
This PR removes the individual Boolean day properties from `OnceDailyScheduledTriggerFilterResource` and `ContinuousDailyScheduledTriggerFilterResource` and replaces it with a bitmask enum.
when serializing DaysOfWeek to JSON, it will serialize to an array of strings e.g. `"DaysOfWeek": ["Monday", "Tuesday", "Wednesday"]`
> Changed scheduled triggers to use an enum for days of week

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Repositories/Async/BuiltInPackageRepositoryRepository.cs
- source/Octopus.Client/Repositories/BuiltInPackageRepositoryRepository.cs
- source/Octopus.Client/Util/HashCalculator.cs
- source/Octopus.Client/Util/HashCodeCombiner.cs
- source/Octopus.Client/Util/PackageContentComparer.cs
Fixes OctopusDeploy/Issues#6055
It takes a long time to upload a large (< 2GB) file to Hosted v1 and Hosted v2. The data gets persisted relatively quickly but the client, in this case, otcto.exe,  doesn't get notified about this and waits until the call times out. 
**Before**
Data uploaded successfully but the client throws `TimeoutException`.
**Now**
We still wait until the timeout exception but this time the overall command succeeds.
When the client gets `TimeoutException` it checks whether the package has been uploaded successfully.  If it has, it doesn't return an error.
We still don't know what the causes the delay but this change at least helps our Cloud customers to work around the problem.  If you compare the time when the client finished and the time when the package was uploaded …
> Don't assume the file hasn't been uploaded

- source/Octopus.Client.Tests/ServerVersionCheckFixture.cs
- source/Octopus.Client/Validation/ServerVersionCheck.cs
Our build version usually have a pre-release tag, so the tests fail miserably 😢
> Make client version checks ignore pre-release tags

- source/Octopus.Client.E2ETests/Octopus.Client.E2ETests.csproj
- source/Octopus.Client.Tests/Octopus.Client.Tests.csproj
We were getting:
```
15:31:34]	Starting: dotnet test source/Octopus.Client.Tests/Octopus.Client.Tests.csproj -c Release -f netcoreapp2.1
[15:31:34]	in directory: /opt/TeamCity/BuildAgent/work/d8818cc5a2905d1
[15:31:34]	Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
[15:31:34]	Copyright (C) Microsoft Corporation. All rights reserved.
[15:31:34]	
[15:31:35]	  Restore completed in 48.19 ms for /opt/TeamCity/BuildAgent/work/d8818cc5a2905d1/source/Octopus.Client/Octopus.Client.csproj.
[15:31:35]	/opt/TeamCity/BuildAgent/work/d8818cc5a2905d1/source/Octopus.Client.Tests/Octopus.Client.Tests.csproj : warning NU1603: Castle.Core 4.0.0 depends on System.ComponentModel.TypeConverter (>= 4.0.1) but System.ComponentModel.TypeConverter 4.0.1 was not found. An approximate best match …
```
> Upgrade teamcity libs to work with newer netcore sdk

- source/Octopus.Client.Tests/Repositories/Async/BasicRepositoryFixture.cs
- source/Octopus.Client.Tests/Repositories/BasicRepositoryFixture.cs
- source/Octopus.Client/Repositories/Async/BasicRepository.cs
- source/Octopus.Client/Repositories/Async/MixedScopeBaseRepository.cs
- source/Octopus.Client/Repositories/BasicRepository.cs
OctopusClient needs to be updated to handle connecting to a server that does not know about spaces
Internal links:
https://trello.com/c/W7Tj8qJI/2675-bug-in-octopusclients-prevents-it-from-being-used-with-non-space-supported-servers
> Bug in OctopusClients prevents it from being used with non-space supported servers

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Repositories/Async/VariableSetRepository.cs
- source/Octopus.Client/Repositories/VariableSetRepository.cs
We had the `/api/variables/all` endpoint exploding when we introduced runbooks, and nobody noticed because we don't have any tests around this endpoint 😢 and clients wasn't even exposing this particular endpoint. If our API supports it, we should be including it in clients, even if customers _should_ be using the other variable endpoints available in other repositories.
Also noticed the variables/preview endpoint was not included in clients too.
> Adding missing endpoints to variables repositories

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/WebPortalConfigurationResource.cs
xFrameOptionAllowFrom has been marked as deprecated as allow-from has been deprecated: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
new option XFrameOptions added which allows customers to set x-frame-options header to sameorigin, deny etc.
https://trello.com/c/qMkihfxa/2944-x-frame-options
Fixes https://github.com/OctopusDeploy/Issues/issues/6196
> Add xFrameOptions configure option and deprecate xFrameOptionAllowFrom

- source/Octopus.Client/Model/ScopeField.cs
This PR resolves an exception when loading `VariableSets`
> Added `ParentDeployment` to ScopeField enum

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ScopeField.cs
To fix customers who might hit deserialization errors if the enum is sent from the server
> Bring ScopeField enum into sync with server

- source/Octopus.Client/LocationChecker.cs
- source/Octopus.Client/Octopus.Client.csproj
- source/Octopus.Client/OctopusAsyncRepository.cs
- source/Octopus.Client/OctopusRepository.cs
This causes trouble with NETFramework vs NETCore, especially in PowerShell 5.
> Add a deprecation notice when client is being used from server's folder

- source/Octopus.Client.Tests/Octopus.Client.Tests.csproj
The version of Assent used in Clients did not support finding any reporters on linux so bumping to this version will at least support vscode as a reporter.
> Bump assent v1.5.0

- source/Octopus.Client/Model/VersionControlSettingsResource.cs
just a one-liner to initialise `VersionControlSettingsResource.Password`
> initialise sensitive value to avoid nullrefs

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/Endpoints/AgentlessEndpointResource.cs
- source/Octopus.Client/Model/Endpoints/AzureWebAppEndpointResource.cs
- source/Octopus.Client/Model/Endpoints/CloudRegionEndpointResource.cs
- source/Octopus.Client/Model/Endpoints/CloudServiceEndpointResource.cs
- source/Octopus.Client/Model/Endpoints/KubernetesEndpointResource.cs
- source/Octopus.Client/Model/Endpoints/OfflineDropEndpointResource.cs
- source/Octopus.Client/Model/Endpoints/ServiceFabricEndpointResource.cs
- source/Octopus.Client/Model/Endpoints/SshEndpointResource.cs
We've removed this on the Server side, so it makes sense to remove it here too.
Can we safely remove this intermediate class without breaking people?
> Remove AgentlessEndpointResource, it's a weird abstraction

- source/Octopus.Client/Repositories/Async/RunbookRepository.cs
- source/Octopus.Client/Repositories/RunbookRepository.cs
We need to tighten the window for version tolerance for the runbook run command in the CLI.
The first step is having the client help us route to the right endpoint given the server version.
> Ensures runbook run commands inspect for server version >= 2020.3.1

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/CommitResource.cs
- source/Octopus.Client/Model/VersionControlBranchResource.cs
- source/Octopus.Client/Repositories/Async/DeploymentProcessRepository.cs
- source/Octopus.Client/Repositories/Async/ProjectRepository.cs
- source/Octopus.Client/Repositories/DeploymentProcessRepository.cs
- source/Octopus.Client/Repositories/ProjectRepository.cs
Background
===
As a part of the Configuration As Code: Multi Branch Round Trip pitch, we will be implementing the ability to select a branch within the Octopus user interface.
This PR adds client methods for endpoints created in https://github.com/OctopusDeploy/OctopusDeploy/pull/6444 and https://github.com/OctopusDeploy/OctopusDeploy/pull/6408
These methods will be used to create e2e tests for the server application.
**Do not merge** until https://github.com/OctopusDeploy/OctopusDeploy/pull/6444 is merged
> Adds beta config-as-code endpoints

- source/Octopus.Client/Model/DeploymentStepResource.cs
There is a helper method in Octopus client to add a package action to a step. The action configuration in that method is outdated, relying on some poly filling on the Octopus Server to configure the step correctly. This PR adds a package reference to the action configuration, which will configure the action correctly without poly filling on the Octopus Server.
> Add package reference when creating package action

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/GitRefType.cs
- source/Octopus.Client/Model/ReleaseResource.cs
Adding VCS properties on Release resource
Related https://octopusdeploy.slack.com/archives/C01AJE4K3T2/p1600657024020300 - We should be adding `Experimental` or `EarlyAccessFeature` attributes to properties like this, however this can b done in a later PR
> Add git reference properties to Release resource

- source/Octopus.Client.Tests/Integration/OctopusClient/CompressionTests.cs
- source/Octopus.Client/OctopusAsyncClient.cs
- source/Octopus.Client/OctopusClient.cs
The client library doesn't take advantage of compression features of HTTP by sending the `Accept-Encoding` header. This PR sets the `AutomaticDecompression` option, which will handle setting the appropriate header and performing the decompression of the result stream automatically.
> Support compression

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/GitRefType.cs
- source/Octopus.Client/Model/ReleaseResource.cs
Removing the GitRefType on the release resource. 
If the consumer wants to release from a tag called 1.0.0, but they also have a branch called 1.0.0, we expect a full name - refs/tags/1.0.0. Otherwise we use the branch 1.0.0
we will always assume a GitRef value is a branch, if a full ref hasn't been provided
main - branch
1.0.0 - branch
refs/heads/main - branch
refs/heads/1.0.0 - branch
refs/tags/main - tag
refs/tags/refs/heads/main - tag
refs/tags/1.0.0 - tag
> Remove GitRefType on Release resource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ReleaseResource.cs
- source/Octopus.Client/Model/VersionControl/VersionControlReferenceResource.cs
Combining the GitRef and GitCommit to 1 type, where the GitCommit is readonly and GitRef is only writeable on create.
> combine 2 related git properties on release to 1 type

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/IOctopusAsyncClient.cs
- source/Octopus.Client/IOctopusClient.cs
- source/Octopus.Client/OctopusAsyncClient.cs
- source/Octopus.Client/OctopusClient.cs
This PR adds a way to call `Delete` with a resource as the body of the request. This is required for config-as-code runbooks, where we want to allow a user to supply a commit message (via the request body) when deleting a runbook.
Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE
> Allow `Delete` calls to include a resource.

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ApiKeyResource.cs
- source/Octopus.Client/Model/PropertyValueResource.cs
- source/Octopus.Client/Model/SensitiveValue.cs
- source/Octopus.Client/Repositories/Async/UserRepository.cs
- source/Octopus.Client/Repositories/UserRepository.cs
Create asymmetric ApiKey resources to match the changes in the Server.
Add support for the Hint property within SensitiveValue.
Used in [Server PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/7542)
[Trello Card](https://trello.com/c/iJGDDeQk/398-display-masked-api-key)
> Add Support for API Key Hints

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ApiKeyResource.cs
- source/Octopus.Client/Repositories/Async/UserRepository.cs
- source/Octopus.Client/Repositories/UserRepository.cs
This PR is part of the [API Key Management](https://docs.google.com/document/d/1BwF_RjvOAX0Rc-6JEr3D1w88BJcyqxXuhYr8GPpV5Gc/edit#) pitch.
Allows setting and retrieving an expiry date for an API key.
Related to Server PR https://github.com/OctopusDeploy/OctopusDeploy/pull/7575.
> Add expiry date to API keys

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.cs
- source/Octopus.Client/Model/CommitResource.cs
- source/Octopus.Client/Model/VersionControl/ConvertProjectToVersionControlledCommand.cs
- source/Octopus.Client/Model/VersionControl/ConvertProjectToVersionControlledResponse.cs
- source/Octopus.Client/Repositories/Async/ProjectRepository.cs
- source/Octopus.Client/Repositories/ProjectRepository.cs
We have a need in Server to pass commit messages and other paraphernalia through when performing actions.
This PR adds a command DTO and corresponding method on the `IProjectBetaRepository` to allow us to convert projects to version-controlled and pass through a commit message.
> Add command and response DTOs for converting projects to version-controlled

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/VersionControlBranchResource.cs
- source/Octopus.Client/Repositories/Async/ProjectRepository.cs
- source/Octopus.Client/Repositories/ProjectRepository.cs
The server now returns a `ResourceCollection` of `VersionControlBranchResource` instead of array.
This relates to the server PR https://github.com/OctopusDeploy/OctopusDeploy/pull/7637
> Expect page metadata in branch response

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/VersionControlSettingsResource.cs
Added a `BasePath` property to the `VersionControlSettingsResource` allowing for the ability to specify a base path for the Octopus project's .ocl files as part of Config as Code.
> Added BasePath to VersionControlSettingsResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/VersionControl/ConvertProjectToVersionControlledResponse.cs
- source/Octopus.Client/Model/VersionControl/IHaveCustomerVisibleMessages.cs
- source/Octopus.Client/Model/VersionControl/MessageCollection.cs
The response when converting a project to version control now includes messages about what happened when the project conversion was undertaken.
> Add messages to ConvertProjectToVersionControlledResponse

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/IOctopusSpaceAsyncRepository.cs
- source/Octopus.Client/IOctopusSpaceRepository.cs
- source/Octopus.Client/Model/DeploymentConnectivityPolicy.cs
- source/Octopus.Client/Model/DeploymentSettingsResource.cs
- source/Octopus.Client/Model/ProjectResource.cs
- source/Octopus.Client/Model/RunbookResource.cs
- source/Octopus.Client/Model/VcsRunbookResource.cs
- source/Octopus.Client/OctopusAsyncRepository.cs
- source/Octopus.Client/OctopusRepository.cs
- source/Octopus.Client/Repositories/Async/DeploymentSettingsRepository.cs
- source/Octopus.Client/Repositories/DeploymentSettingsRepository.cs
Adds support for deployment settings endpoints.
*Note:* this is a breaking change for VCS projects.
See [Config-as-Code: Project Settings API](https://github.com/OctopusDeploy/Architecture/blob/master/OctopusServer/ConfigAsCode/ConfigAsCodeSettingsAPI.md)
All projects get/update deployment-related settings via get/modify Project.
Get/Modify Project endpoints:
- Maintain backwards compatibility for db projects. 
- Deployment Settings are no longer populated for VCS projects 
_in future this will be a [Bad Request](https://github.com/OctopusDeploy/Architecture/blob/master/OctopusServer/ConfigAsCode/ConfigAsCodeSettingsAPI.md#considered-solution-3) - see [implementation](https://github.com/OctopusDeploy/OctopusDeploy/pull/8073/files#diff-4809639251bd9cfba039cb763e088a5632123ede8e8c11c9b8765e2 …
> Separate deployment settings API and resource

- build/Build.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Repositories/ChannelRepository.cs
We support the `/all` endpoint in[ OctopusServer for Channels](https://github.com/OctopusDeploy/OctopusDeploy/blob/1f1a7a667daa86a14e8dee4f448d346c3b673389/source/Octopus.Server/Web/Api/Actions/Channels/ChannelsNancyModule.cs#L27) so in to synchronize the surface area we should probably ensure the C# client can interact with it.
> Add IGetAll<> interface to the IChannelRepository

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Operations/InvalidRegistrationArgumentsException.cs
- source/Octopus.Client/Operations/RegisterMachineOperation.cs
- source/Octopus.Client/Operations/RegisterWorkerOperation.cs
This PR changes the type of exception thrown when validation arguments for the `register-with` and `register-worker` commands from `ArgumentException` to a new custom type `InvalidRegistrationArgumentsException`, so we can handle it better.
The new type inherits from `ArgumentException`, so this should be backwards compatible.
This PR is required by https://github.com/OctopusDeploy/OctopusTentacle/pull/282.
Please confirm my thinking that this is backwards compatible.
Other than that, :eyes: and a 💚 build should be sufficient for this PR.
> Improve Tentacle command line validation

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/CommunicationStyle.cs
- source/Octopus.Client/Model/Endpoints/StepPackageEndpointResource.cs
- source/Octopus.Client/Serialization/EndpointConverter.cs
Adds StepPackageEndpointResource to the client to enable integration tests within Server. Due to endpoints using a custom serializer this is not possible to do by extending Client within Server project.
> Add step package deployment targets

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Repositories/Async/DeploymentSettingsRepository.cs
Deployment Settings props on `ProjectResource` have been [deprecated](https://github.com/OctopusDeploy/OctopusClients/blob/8a6acb14a9e412d5829560cebd2963d86a89dccd/source/Octopus.Client/Model/ProjectResource.cs#L94). This was done to unlock functionality for Config as Code - allowing these settings to persist to git. 
The supported path forward for Database Projects (i.e. traditional non-version controlled projects in Octopus Deploy) is to modify these settings via 
```http
POST api/projects/{projectId}/deploymentsettings
``` 
In future `POST projects/{projectId}/{gitRef}/deploymentsettings` will also be supported.
```csharp
octopusRepository.Client.Post($"projects/{projectResource.Id}/deploymentsettings", deploymentSettingsResource);
```
This PR provides a strong typing for the supported …
> Add non-beta path for Deployment Settings endpoints

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/ChannelResource.cs
- source/Octopus.Server.Client/Model/IHaveProject.cs
- source/Octopus.Server.Client/Repositories/Async/ChannelRepository.cs
- source/Octopus.Server.Client/Repositories/Async/IGet.cs
- source/Octopus.Server.Client/Repositories/Async/ProjectScopedRepository.cs
- source/Octopus.Server.Client/Repositories/ChannelRepository.cs
- source/Octopus.Server.Client/Repositories/IGet.cs
- source/Octopus.Server.Client/Repositories/ProjectScopedRepository.cs
As we move towards a world where where project scoped resources (E.g. Channels) are accessed using the project route (`/projects/{projectId}/channels`) rather than their standalone routes (`/channels`), we're gonna see our C# client library change to reflect that.
This PR introduces a new Repository implementation based off of the `BasicRepository<TResource>`, which has project scoped methods for creating and getting resources.
Modifying and Deleting resources _shouldn't_ need their own project-scoped methods, as they use the "Self" links populated by Octopus Server.
This _should_ make converting new resources to use the project-scoped routes much easier in the future. the only changes that will be required are:
1. Ensure the resource implements the `IHaveProject` interface
2. Change the …
> Added a Repository implementation for project-scoped resources

- source/Octopus.Client.Tests/Integration/HttpIntegrationTestBase.cs
- source/Octopus.Client.Tests/Integration/Repository/MachineRepositoryTest.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Endpoints/StepPackageEndpointResource.cs
Small fix to allow `StepPackageEndpointResource.Inputs` to be passed as an object (with an unknown set of properties). This is serialized into `DeploymentActionInputs` in Server.
Parent PR: https://github.com/OctopusDeploy/OctopusDeploy/pull/9082
> Structured Inputs for StepPackageEndpointResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Triggers/ScheduledTriggers/DeployNewReleaseActionResource.cs
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/9452
For Deploy new release we need to do the following to support Git:
* We will have two additional fields, one to select a git ref and one to select a channel from the git ref.
* We will then be able to get the list of environments made available by the lifecycle on the selected channel.
`DeployNewReleaseActionResource` has a new field: `VersionControlReference` to support selecting a Channel from a GitRef for VCS DeployNewRelease Actions
> Adding VersionControlReference to DeployNewReleaseActionResource

- .nuke/build.schema.json
- build/Build.cs
- build/_build.csproj
Updates the `build.schema.json` file with the latest changes.
Fixes up a few resharper warnings.
Bumps to latest Nuke.Common and Nuke.OctoVersion.
> Minor nuke file cleanup

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Repositories/Async/ChannelRepository.cs
- source/Octopus.Server.Client/Repositories/Async/DeploymentProcessRepository.cs
- source/Octopus.Server.Client/Repositories/Async/DeploymentSettingsRepository.cs
- source/Octopus.Server.Client/Repositories/Async/ProjectRepository.cs
- source/Octopus.Server.Client/Repositories/Async/ProjectScopedRepository.cs
- source/Octopus.Server.Client/Repositories/ChannelRepository.cs
- source/Octopus.Server.Client/Repositories/DeploymentProcessRepository.cs
- source/Octopus.Server.Client/Repositories/DeploymentSettingsRepository.cs
- source/Octopus.Server.Client/Repositories/ProjectRepository.cs
- source/Octopus.Server.Client/Repositories/ProjectScopedRepository.cs
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/9495 (internal link)
- Gives the user a meaningful error rather than a response from the wrong endpoint.
- Adds a fallback to current repos from beta so that we can use the beta API for both DB and Git Projects
> Handle partially-resolved project-scoped route templates for vcs resources (i.e. routes missing gitRef)

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Repositories/Async/ProjectRepository.cs
- source/Octopus.Server.Client/Repositories/ProjectRepository.cs
Runbooks are not yet version controlled, so the route for this operation has been removed. We'll re-add this in the future once we migrate Runbooks to version control.
> Remove GetAllRunbooks operation from beta repository

- source/Octopus.Server.Client/Repositories/Async/ProjectRepository.cs
- source/Octopus.Server.Client/Repositories/ProjectRepository.cs
Previously the project route would be pre-populated with the default gitref. As a result any of the channel requests would need to first go through the branches endpoint to get the appropriate route.
Now that the project route is again non-version controlled, and the routes within a project are templated, we can simply use these routes directly.
> No need to use Branch endpoint to get channel route now project link is templated

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/CreateChannelCommand.cs
- source/Octopus.Server.Client/Model/ICommitCommand.cs
- source/Octopus.Server.Client/Model/ModifyChannelCommand.cs
- source/Octopus.Server.Client/Model/ModifyDeploymentProcessCommand.cs
- source/Octopus.Server.Client/Model/ModifyDeploymentSettingsCommand.cs
- source/Octopus.Server.Client/Repositories/Async/ChannelRepository.cs
- source/Octopus.Server.Client/Repositories/Async/DeploymentProcessRepository.cs
- source/Octopus.Server.Client/Repositories/Async/DeploymentSettingsRepository.cs
- source/Octopus.Server.Client/Repositories/ChannelRepository.cs
- source/Octopus.Server.Client/Repositories/DeploymentProcessRepository.cs
- source/Octopus.Server.Client/Repositories/DeploymentSettingsRepository.cs
- source/Octopus.Server.Client/Serialization/Serializer.cs
and consolidate commit/non-commit requests into the same resource/command. 
This improves the migration story for anyone converting to source control, and lowers our maintenance burden by getting us one step closer to having consolidated endpoints for project-scoped routes that may or may not include a `{gitRef}`.
[Trello card](https://trello.com/c/vbcFEmA5/359-commit-message-middleware) (internal link), relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/9735
These changes are backwards-compatible with our existing DB routes, but are a breaking change for our `{gitRef}`'d routes, because they remove the need for a `CommitResource` wrapper around Create and Modify requests.
API consumers would need to a branching code-path to deal with commit messages based on if …
> Add modify commands for version-controlled resources

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/DeploymentTargets/DeploymentTargetTaskType.cs
- source/Octopus.Server.Client/Repositories/MachineRepository.cs
This PR is for exposing the new parameter `type` on `GET /machines/{id}/tasks` in Octopus.Client. See https://github.com/OctopusDeploy/OctopusDeploy/pull/9853 (internal) for details
> Add type parameter to Machines.GetTasks

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/ActionTemplateResource.cs
- source/Octopus.Server.Client/Model/CommunityActionTemplateResource.cs
This PR adds new fields for step packages to `ActionTemplateResource` and `CommunityActionTemplateResource`. See https://github.com/OctopusDeploy/OctopusClients/pull/610 for more context on the same fields being added to steps and deployment targets.
> Adds new step package fields to action templates

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Repositories/DeploymentProcessRepository.cs
Does what is says on the tin. Sync was `IDeploymentProcessRepositoryBeta`, async was `IDeploymentProcessBetaRepository`, now they're both `IDeploymentProcessBetaRepository`
> Make naming consistent with async repo

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/FeaturesConfigurationResource.cs
`IsStepUiFrameworkEnabled` feature flag is missing from `FeaturesConfigurationResource`, which resets it to default every time the feature flags are updated (ex. `await repository.FeaturesConfiguration.ModifyFeaturesConfiguration(featuresConfiguration);`)
This PR adds `IsStepUiFrameworkEnabled` property to `FeaturesConfigurationResource`.
> Add IsStepUiFrameworkEnabled feature flag

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/IOctopusSystemAsyncRepository.cs
- source/Octopus.Server.Client/IOctopusSystemRepository.cs
- source/Octopus.Server.Client/Model/TelemetryConfigurationResource.cs
- source/Octopus.Server.Client/Model/UpgradeConfigurationResource.cs
- source/Octopus.Server.Client/OctopusAsyncRepository.cs
- source/Octopus.Server.Client/OctopusRepository.cs
- source/Octopus.Server.Client/Repositories/Async/TelemetryConfigurationRepository.cs
- source/Octopus.Server.Client/Repositories/TelemetryConfigurationRepository.cs
We've changed the way how Octopus Deploy collects and sends telemetry, for better transparency and visibility.
This PR introduces a telemetry configuration repository to easily enable/disable telemetry
> Introduce telemetry configuration repository

- build/Build.cs
- source/Octopus.Client.E2ETests/Octopus.Client.E2ETests.csproj
- source/Octopus.Client.E2ETests/OctopusClientsCanBeMockedFixture.cs
- source/Octopus.Client.Tests/OctopusClientsCanBeMockedFixture.cs
Fixes #635.
This PR ensures that all relevant Octopus-defined types keep their existing visibility (i.e. `public`) when being ILMerged into a single `Octopus.Client.dll`.
It also works around an apparent bug in `il-repack` which ignores type name exclusions.
1. Run up a new C# solution. A simple console app is fine.
2. Restrict the package sources to nuget.org and `Install-Package Octopus.Client`
3. Observe that the `ICommand<,>` interface is marked as internal. (Try to define a type which implements it and it will go red pretty quickly.)
4. Remove the package reference.
5. Restrict the package sources to the Octopus internal NuGet feed and `Install-Package Octopus.Client -Pre -Version 11.4.3622-bug-ilmerging-internalises-public-interfaces`
6. Observe that the test code now compiles.
> Keep all Octopus types public when ILMerging

- build/Build.cs
- source/Octopus.Client.E2ETests/InlinedDependenciesFixture.cs
We recently adjusted ILMerge settings to ensure that types from `Octopus.Server.MessageContracts.Base` and `Octopus.Server.MessageContracts.Base.HttpRoutes` remained public after an ILMerge. We brought all of the Octopus.* types along with that change, only to discover that there are some usages where there is now a conflict with some users' references to `Octopus.TinyTypes.*`.
Ultimately, the single ILMerged client will need some more invasive surgery before it can support API vNext payloads. Until then, though, its knowledge of Octopus.TinyTypes.* can (and should) be kept internal.
> Make Octopus.TinyTypes.* internal again when ILMerging.

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client.Tests/Serialization/PermissionSerializationFixture.cs
- source/Octopus.Server.Client/Model/Permission.cs
- source/Octopus.Server.Client/Repositories/Async/UserRolesRepository.cs
- source/Octopus.Server.Client/Repositories/UserRolesRepository.cs
- source/Octopus.Server.Client/Serialization/JsonSerialization.cs
- source/Octopus.Server.Client/Serialization/PermissionConverter.cs
The Permission enum causes us issues every time a new permission is added to server. Older versions of client talking to newer versions of server with new permissions cause the Json deserialization to throw an exception when it doesn't recognise an enum value. This is the nature of enums.
In Octopus server itself, and in our other client libraries, we have moved most things away from using enums now. The preferred option over enums is a class that represents the same value but internally is just the string value off the wire.
To show some examples, the AdministerSystem permission is now defined as follows on the permissions class.
```
public static readonly Permission AdministerSystem = new Permission("AdministerSystem");
```
The Permission class itself is implementing `IEquatable` and …
> Changing Permission to not be an enum

- source/Octopus.Client.Tests/Repositories/ProjectRepositoryFixture.cs
- source/Octopus.Server.Client/Repositories/Async/ProjectRepository.cs
- source/Octopus.Server.Client/Repositories/ProjectRepository.cs
We changed the name of the link that's used when converting projects to Git (from `ConvertToVcs` to `ConvertToGit`). This is part of a longer term goal to change all of our usages of `Vcs` to `Git`.
To make this transition as smooth as possible, the projects links collection for a project contains both of these links for the time being, so older versions of client would continue to work with newer versions of Octopus.
But I didn't cater for using a newer version of client with an older version of Octopus. Client is looking for `ConvertToGit` but older versions of Octopus are only returning the `ConvertToVcs` link. This closes that loop, falling back to the old link if the new one is not there.
> Fall back to ConvertToVcs link if there is no ConvertToGit link

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Permission.cs
As part of the changes in https://github.com/OctopusDeploy/OctopusDeploy/pull/12325, we added two new enum for permissions. 
This PR update the client have matching resources.
> Added new permission enums

- .nuke/build.schema.json
- build/Build.cs
- build/_build.csproj
Code signing stopped working after EngProd removed .NET Core 2.1 from our build system.
This PR updates AzureSignTool to version 3.0.0 and adds the `AzureKeyVaultTenantId` parameter. I also added the `AzureKeyVaultTenantId` to the [build parameters](https://build.octopushq.com/admin/editBuildParams.html?id=buildType:OctopusDeploy_OctopusClients_BuildOctopusClients).
These changes are based on these other ones:
* https://github.com/OctopusDeploy/OctopusDeploy/pull/11997/commits/b7f55e6c0d0d6776d52dfb58bdf25f9b2e32b4d2
* https://github.com/OctopusDeploy/OctopusDeploy/pull/11997/commits/1757bcd80e0fad023f1dba90e077ef1493101615
> Fix DLL signing after we dropped .NET Core 2.1

- build/Build.cs
- build/_build.csproj
- source/Octopus.Client.Tests/Octopus.Client.Tests.csproj
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
While doing preparation work for the .Net 6 migration it was discover we have a failing unit test (ThePublicSurfaceAreaShouldNotRegress) when testing .Net Framework. The failing test was investigated to discover how the build pipeline was functioning if this was not succeeding.
Discoveries
* The unit tests can only run against .Net Framework in a Windows environment
* The units tests were not being called in the Windows environment
* The unit tests were being called in various Linux environments and passing
* Changes that had been made to the Approved Public Surface for .Net Core had not been made to .Net Framework
This PR seeks to solve the problem by
* Including the unit tests in the Build process, to ensure they are run in the build environment(Windows)
* Updated the Approved Public …
> Added depends on tests to build, made framework approved public surface file match core version

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/FeaturesConfigurationResource.cs
The JSM Deployment Blocking Integration is now protected via a licence flag, and no longer requires a feature flag - as such, the flag is being removed.
> Remove IsJiraServiceManagementIntegrationEnabled flag

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/IOctopusCommonAsyncRepository.cs
- source/Octopus.Server.Client/IOctopusCommonRepository.cs
- source/Octopus.Server.Client/Model/EventRetention/ArchivedEventFileResource.cs
- source/Octopus.Server.Client/Model/EventRetention/EventRetentionConfigurationResource.cs
- source/Octopus.Server.Client/OctopusAsyncRepository.cs
- source/Octopus.Server.Client/OctopusRepository.cs
- source/Octopus.Server.Client/Repositories/ArchivedEventFileRepository.cs
- source/Octopus.Server.Client/Repositories/Async/ArchivedEventFileRepository.cs
The new Event Retention feature was added to Octopus Server. We now want to update the Octopus.Client to reflect the enhancements made.
We now support the 3 endpoints for managing archived event files in the Octopus.Client.
The configuration resource was also added to support using the configuration endpoint with this new feature.
Octopus Server was updated using the NuGet Package of this PR, and enhanced to use the new methods.
The PR can be found [here](https://github.com/OctopusDeploy/OctopusDeploy/pull/13135)
Is this considered an acceptable level of testing for this change?
This is the first time I have made a change to Octopus.Client. Please make sure I have not overlooked something that needs to be set.
The minimum version required has not been built yet. So this PR cannot be …
> Adding event retention resource and API interfaces

- octoversion.json
For the nightly build, the branch information is `refs/heads/main` and the existing expression is appending `-nightly`.
However, `refs/heads/main-nightly`, is matching the `NonPreReleaseTagsRegex` defined in `octoversion.json`
This results in **no pre-release** tag added for nightly build. 
The original regex captures any additional character / words beyond the condition (main|master...*), which is not correct.
> Fix - Nightly build produces branch TAG

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Repositories/Async/DeploymentProcessRepository.cs
This is a continued effort on initial initiative completed in this [PR](https://github.com/OctopusDeploy/OctopusClients/pull/681).
For this stream, the cancellation token support is added on `IDeploymentProcessRepository`.
All existing methods that doesn't take cancellation token are marked with `Obsolete`
The guidance on adding cancellation token overload is to maintain compliance with **[CA1068: CancellationToken parameters must come last](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1068)**
> Add cancellation token support for IDeploymentProcessRepository

- .github/workflows/main.yaml
Some test failures were complaining because they couldn't find a `diff` program. This is because Assent will attempt to display a diff by default. This PR disables that assent behaviour.
> Set AssentNonInteractive for test runs.

- source/Octopus.Server.Client/Octopus.Server.Client.csproj
The previous version of the Client was targeting a version of Octopus.Server.MessageContracts.Base that was not publicly  accessible. Octopus.Client has the version of the message contracts merged so was not affected. But Octopus.Server.Client does not have it's dependencies merged so could not be used.
> Updated versio of MessageContracts.Base and MessageContracts.Base.HttpRoutes

- source/Octopus.Server.Client/Octopus.Server.Client.csproj
I updated Octodiff to 2.0.100. See the lastest Octodiff PR [here](https://github.com/OctopusDeploy/Octodiff/pull/39).
I don't expect the mentioned PR to make much difference on OctopusClients since the fix targets Octopus Server and Calamari. However, I would like to keep Octodiff up to date here because I changed one public interface.
[sc-25897]
> Update Octodiff to 2.0.100

- .github/workflows/main.yaml
`AssentNonInteractive` was only being set on select build jobs. We need to set the value on all of them, so all the test runs pick them up.
> Set AssentNonInteractive for all build jobs

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Triggers/ScheduledTriggers/DailyScheduledTriggerFilterResource.cs
- source/Octopus.Server.Client/Model/Triggers/ScheduledTriggers/DailyScheduledTriggerInterval.cs
- source/Octopus.Server.Client/Model/Triggers/ScheduledTriggers/DaysPerWeekScheduledTriggerFilterResource.cs
- source/Octopus.Server.Client/Model/Triggers/ScheduledTriggers/ScheduledTriggerFilterRunType.cs
- source/Octopus.Server.Client/Model/Triggers/TriggerFilterResource.cs
- source/Octopus.Server.Client/Serialization/TriggerFilterConverter.cs
We had some scheduled triggers and enums present in our core model but not in our client models
This PR looks to match up the two!
> Add missing scheduled project triggers

- build/Build.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/PermissionDescription.cs
- source/Octopus.Server.Client/Repositories/Async/UserPermissionsRepository.cs
[The API controller is here](https://github.com/OctopusDeploy/OctopusDeploy/blob/431e99f2f127352dfc137eef376444ce7a72df98/source/Octopus.Server/Web/Api/Actions/PermissionDefinitionsResponder.cs#L22)
While porting the API to ASP.NET (https://github.com/OctopusDeploy/OctopusDeploy/pull/15443) I found that the method didn't actually return any data because the response was in a completely different shape.
I decided to obsolete it to keep compat, but I doubt anyone is actually using it.
[sc-32326]
> Obsoleted `UserPermissionsRepository.GetConfiguration` and replaced it with `GetDescriptions` which returns the right type

- source/Octopus.Client.Tests/Integration/OctopusClient/TimeoutTests.cs
- source/Octopus.Server.Client/OctopusAsyncClient.cs
Regardless of what the actual cause of cancellation was, `DispatchRequest` squashes any cancellation exception in favour of a `TimeoutException`. This means if your own code makes a request and then cancels it immediately for whatever reason, you get the following misleading error:
```
System.TimeoutException: Timeout getting response from [...] (client timeout is set to 00:04:00).
```
This also means that user code that wants to squash a cancellation exception caused by their own token (e.g. during application shutdown, when cancellation should happen silently and not throw) cannot do so.
This PR:  
* Fixes that issue by specifically replacing the exception when it was genuinely caused by a timeout
* Keeps the original exception around as an inner exception as a matter of best practice
* …
> Don't overwrite genuine cancellation exceptions with timeout exceptions in DispatchRequest

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/SpaceResource.cs
Private spaces [have been decommissioned](https://docs.google.com/document/d/1fTe8ea1bSrMKhCQdb6-NSytQYcubV_d9RNIbIAR4kuE). This PR removes `PrivateSpaceOwner` column, which is no longer used anywhere.
> Remove PrivateSpaceOwner property

- source/Octopus.Client.Tests/Serialization/CrossPlatformDateTimeZoneJsonConverterFixture.cs
- source/Octopus.Client.Tests/Serialization/PermissiveInstantJsonConverterFixture.cs
`PermissiveInstantJsonConverterFixture` and `CrossPlatformDateTimeZoneJsonConverterFixture` had a tricky implicit assumption that a timezone always remains with the same offset, which is not true for timezones with daylight savings time (like Victoria). Making the tests fail when the offset is different from the verified date's offset.
The fix is to always use the offset as it was at the time when the check is made and not today's offset.
> Fix datetime serialization tests

- source/Octopus.Client.Tests/Integration/OctopusClient/FileTests.cs
- source/Octopus.Server.Client/OctopusClient.cs
We previously updated our client to include a [trailing boundary](https://github.com/OctopusDeploy/OctopusClients/pull/720), but unfortunately during a rebase it was removed by accident. This PR fixes this oversight and adds the appropriate trailer boundary back into multipart data data being sent via the sync client.
> Fix multipart trailer for sync client

- .github/workflows/main.yaml
In order to simplify the code used to test Octopus Clients against a variety of Linux distributions, it has been converted to use Matrix in the build process.
Significantly reduces the size of the workflow.
> Convert to us GHA matrix

- build/containers/test-base/rocky9/Dockerfile
Nightly build had started failing. A check of the logs revealed that gzip was missing. It was not missing before, but I guess this is why we do nightly builds. I have added gzip to the rocky9 test process and all seems to work correctly now.
> Fix Rocky Linux 9 build and test

- source/Octopus.Client.Tests/Integration/HttpIntegrationTestBase.cs
- source/Octopus.Client.Tests/Integration/OctopusClient/TimeoutTests.cs
- source/Octopus.Server.Client/OctopusAsyncClient.cs
The `HttpIntegrationTestBase` was always setting the Client Options to a non-null value, and hiding possible issues where a null value was allowed on the `Create` methods.
Related to https://github.com/OctopusDeploy/OctopusTentacle/pull/450
[sc-42931]
> ensure client options is never null prior to client creation

- .github/workflows/main.yaml
- build/_build.csproj
[sc-45166]
A nightly build didn't show up in deploy for OctopusClients. This is because there was a network timeout while pushing the nuget packages to octopus. The current version of the `push-packages-action` (v1) installs the .NET CLI and uses it to push packages. It was this installation that timed out.
This PR updates `push-packages-action` to v3 as it doesn't need the CLI at all.
It also updates the `setup-dotnet` action to v3 to stop the `Node.js 12 actions are deprecated.` warnings in the action logs.
We will still see the `The set-output command is deprecated and will be disabled soon` warning for now. We need swap over to `Octopus.OctoVersion.Tool` from `OctoVersion.Tool` to fix these warnings but that is blocked until https://github.com/nuke-build/nuke/pull/1104 is released in …
> Update push-package and setup-dotnet actions

- source/Octopus.Server.Client/OctopusAsyncClient.cs
`options` (not validated against null) instead of `clientOptions` is used in `OctopusAsyncClient` constructor, which will lead to `NullReferenceException` if passed `options` was null.
> Fix null reference exception when passing null as options in async client

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/MachinePolicyResource.cs
- source/Octopus.Server.Client/Model/MachineRpcCallRetryPolicy.cs
Add new properties for RPC retries to MachinePolicy, as part of [sc-46289].
> Add RPC retry policy

- source/Octopus.Client.Tests/Octopus.Client.Tests.csproj
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Server.Client/Model/FeedType.cs
- source/Octopus.Server.Client/Model/OciRegistryFeedResource.cs
- source/Octopus.Server.Client/Serialization/FeedConverter.cs
This PR adds the new OCI Registry feed type as we're adding support for OCI Registries in Octopus Server.
[sc-43537]
> add oci registry feedtype enum and resource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Server.Client/Extensions/StringExtensions.cs
- source/Octopus.Server.Client/Repositories/Async/BasicRepository.cs
- source/Octopus.Server.Client/Repositories/Async/IFindByPartialName.cs
- source/Octopus.Server.Client/Repositories/Async/TenantRepository.cs
- source/Octopus.Server.Client/Repositories/BasicRepository.cs
- source/Octopus.Server.Client/Repositories/IFindByPartialName.cs
- source/Octopus.Server.Client/Repositories/TenantRepository.cs
Add the ability to find by partial name. Server API has supported this for a while now, just updating client to make use of it.
First one to support this is tenants
Internal discussion with PET team - https://octopusdeploy.slack.com/archives/C04LWDDAC6L/p1689661870773089
> Find by partial name support

- source/Octopus.Server.Client/OctopusAsyncClient.cs
[sc-54145]
[This block](https://github.com/OctopusDeploy/OctopusClients/blob/1e047d18c7ae725b6d9583153137fa04252fb914/source/Octopus.Server.Client/OctopusAsyncClient.cs#L592-L596) overrides the HTTP method to a `POST` if it's a `PUT` or `DELETE`. I'm not entirely sure why this happens. A quick google suggests that it is to get around infrastructure with limitations/restrictions that only allow `GET` or `POST`.
We proceed to log the request URI with this overridden method. This causes confusion when trying to debug issues between client/server since the logged POST hides the actual method and there is no corresponding POST on the Server side.
Example:
This PR changes the log to use the actual request method. The trace log was originally added in …
> Update log to use request method

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/GitDependencyResource.cs
This PR adds the `StepPackageInputsReferenceId` field for git resources, so it can be used from step framework steps.
> Add step package reference id for git resource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Repositories/Async/ProjectRepository.cs
This is a partner PR to https://github.com/OctopusDeploy/OctopusDeploy/pull/19881, which added `releaseHistoryCount` to the project progression link template.
This PR adds the optional `releaseHistoryCount` value when sending a [GetProjectProgressionRequest](https://github.com/OctopusDeploy/OctopusDeploy/blob/2be9c86e473100bf68e83b8bbf3628aa7e03bb38/source/Octopus.Core/Features/Progression/MessageContracts/GetProjectProgressionRequest.cs) from the `IProjectRepostitory`.
[sc-58183]
> Add releaseHistoryCount to GET project progression

- source/Octopus.Server.Client/Model/MachineRpcCallRetryPolicy.cs
Change PRC retries to be on by default and set the retry duration to 2.5 minutes for new machine policies
> Change defaults for RPC Retries

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/ControlType.cs
- source/Octopus.Server.Client/Model/VariableType.cs
[sc-58725]
Related https://github.com/OctopusDeploy/OctopusDeploy/pull/20170
> Add username password account variables and control type

- source/Octopus.Server.Client/Octopus.Server.Client.csproj
So that it gets picked up on our [credits](https://octopus.com/docs/credits) page, which is currently showing undefined.
> Include license in nuget package

- .github/workflows/main.yaml
- build/Build.cs
- source/Octopus.Client.E2ETests/NuSpecDependenciesFixture.cs
- source/Octopus.Client.E2ETests/Octopus.Client.E2ETests.csproj
- source/Octopus.Client.Tests/Octopus.Client.Tests.csproj
- source/Octopus.Client/Octopus.Client.csproj
- source/Octopus.Client/Octopus.Client.nuspec
- source/Octopus.Server.Client/Octopus.Server.Client.csproj
To allow us to upgrade `OctopusClient` in `OctopusTentacle`, we need to support .Net Framework 4.8
Unfortunately when we try and use the .Net Framework 4.6.2 we get some versioning issues with `System.Net.Http`.
In testing, creating a .Net Framework 4.8 version in the Nuget package eliminated the issues.
> Add new net48 build target

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.cs
- source/Octopus.Server.Client/OctopusAsyncClient.cs
- source/Octopus.Server.Client/OctopusClient.cs
- source/Octopus.Server.Client/OctopusServerEndpoint.cs
Adding the ability for OctopusClient to use Tokens for authentication.
This does not include the ability for OctopusClient to facilitate a OIDC Token Exchange, and just allows the client to use a valid JWT Token that it is given.
This is being added so that Tentacle can use a Token to register itself as part of work over in [#project-k8s-agent](https://octopusdeploy.slack.com/archives/C05KK1G85J5). We want to be able to generate a token on server as part of generating a command for the user to run to install the Tentacle on their kubernetes cluster. This means for our use-case, Tentacle does not need to generate its own token and this update can be used instead.
[sc-60667]
> Add support for token authentication

- build/Build.cs
Making a similar change to [this Tentacle change](https://github.com/OctopusDeploy/OctopusTentacle/pull/630) so that when building the package locally it automatically appends a timestamp on the version. This makes iterating on the client a lot quicker.
> Append Timestamp to version when building locally

- source/Octopus.Client.Tests/Integration/OctopusClient/SslTests.cs
[sc-62738]
To help minimise the effort required to upgrade to .NET 8, we're back-porting any .NET 6 compatible changes from our .NET 8 branches.
> .NET 8 prep: Use async method instead

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Endpoints/ListeningTentacleEndpointConfigurationResource.cs
- source/Octopus.Server.Client/Model/Endpoints/PollingTentacleEndpointConfigurationResource.cs
- source/Octopus.Server.Client/Model/Endpoints/TentacleEndpointConfigurationResource.cs
- source/Octopus.Server.Client/Serialization/TentacleConfigurationConverter.cs
I accidentally renamed this property when I was using Rider's refactor.
Just naming back to what I wanted it to be.
> Fix AgentCommunicationMode property name

- source/Octopus.Client.E2ETests/Octopus.Client.E2ETests.csproj
- source/Octopus.Client.Tests/HttpRequestRouting/GivenAGetPayload.cs
- source/Octopus.Client.Tests/HttpRequestRouting/GivenAPostPayload.cs
- source/Octopus.Client.Tests/Integration/OctopusClient/ErrorHandlingTests.cs
- source/Octopus.Client.Tests/Integration/OctopusClient/HttpMethodTests.cs
- source/Octopus.Client.Tests/Integration/OctopusClient/StatusTests.cs
- source/Octopus.Client.Tests/Integration/OctopusClient/StreamTests.cs
- source/Octopus.Client.Tests/Integration/OctopusClient/TimeoutTests.cs
- source/Octopus.Client.Tests/Integration/Repository/UnauthorisedTest.cs
- source/Octopus.Client.Tests/Octopus.Client.Tests.csproj
- source/Octopus.Client.Tests/Operations/RegisterKubernetesClusterOperationFixture.cs
- source/Octopus.Client.Tests/Operations/RegisterMachineOperationFixture.cs
- source/Octopus.Client.Tests/Repositories/Async/BasicRepositoryFixture.cs
- source/Octopus.Client.Tests/Repositories/Async/TaskRepositoryTests.cs
- source/Octopus.Client.Tests/Repositories/BasicRepositoryFixture.cs
- source/Octopus.Client.Tests/Repositories/ProjectBetaRepositoryTests.cs
- source/Octopus.Client.Tests/Repositories/VariableSetBetaRepositoryTests.cs
- source/Octopus.Client.Tests/Serialization/CrossPlatformDateTimeZoneJsonConverterFixture.cs
- source/Octopus.Client.Tests/Serialization/PermissiveInstantJsonConverterFixture.cs
- source/Octopus.Client.Tests/Spaces/MixedScopeSpaceContextExtensionTests.cs
- source/Octopus.Client.Tests/UrlTemplateTests.cs
I'm adding some tests and I've noticed that FluentAssertions is quite behind. I want to use new features so I'm giving updating it a crack. Only changing tests to fix breaking changes in FluentAssertions as we're updating over a few major versions.
I'm thinking if the build goes green we should be good to go 👍
> Update fluent assertions version and fix breaking changes

- source/Octopus.Client.Tests/Operations/RegisterKubernetesClusterOperationFixture.cs
- source/Octopus.Server.Client/Operations/RegisterKubernetesClusterOperation.cs
- source/Octopus.Server.Client/Operations/RegisterMachineOperation.cs
Part of #project-k8s-agent
The standard behaviour for the `register-with` command (which is for register machines, as opposed to workers) will automatically set the `--force` flag. This means that it will "blat" over the existing target in server with whatever has been configured.
The `register-k8s-cluster` command followed the same formula originally but it needs to be updated as this doesn't work with kubernetes very well. As the Kubernetes Tentacle will be running in a cluster (duh), the pod could be stopped and restarted at anytime. If we use the existing functionality, the container will "blat" over the settings in server every time it restarts for whatever reason.
However there is also a risk that if the originally configuration is lost in k8s (if it's using a volume mount, the …
> Ensure k8s reregistration is correctly

- .github/workflows/main.yaml
In a previous PR I updated the GHA workflow `actions/github-script` from `@v3` to `@v7`.
In [v5, github issued a breaking change](https://github.com/actions/github-script#v5), so we need to use `github.rest.git.createRef` rather than `github.git.createRef`
This PR applies that fix
> Fix GitHub script

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/ProjectGitCredentialResource.cs
- source/Octopus.Server.Client/Serialization/GitSettingsConverter.cs
Allows the use of the upcoming GitHub app connections as Config as Code credentials
> Add GitHub credential type for Git persistence settings

- .github/workflows/main.yaml
[sc-67040]
In #810 a GitHub action script was changed to use Bash syntax instead of PowerShell. This step actually runs on Windows using PowerShell, and thus was using the correct syntax already. As a result, nightly releases are now being published as full releases.
Re-instate the PowerShell syntax.
> Re-instate PowerShell syntax

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Triggers/CreateReleaseActionResource.cs
- source/Octopus.Server.Client/Model/Triggers/FeedFilterResource.cs
- source/Octopus.Server.Client/Model/Triggers/TriggerActionResource.cs
- source/Octopus.Server.Client/Model/Triggers/TriggerFilterResource.cs
- source/Octopus.Server.Client/Serialization/TriggerActionConverter.cs
- source/Octopus.Server.Client/Serialization/TriggerFilterConverter.cs
Adds resources required for the new project trigger that creates a new release when new packages are pushed to external feeds.
[sc-68515]
> Add resources for external feed release creation

- .github/workflows/main.yaml
Our API keys periodically expire, breaking things.
Octopus now supports OIDC for github actions, with wildcards on permitted branches, enabling us to authenticate via OIDC and remove the need for API keys entirely.
You can see it in action on this branch build: https://github.com/OctopusDeploy/OctopusClients/actions/runs/7634720752
> Use OIDC to login to deploy, nightly timestamps

- .github/workflows/main.yaml
Note: Unlike all the other repos, I didn't need to update the permissions to allow git tag creation on this workflow.
Because of the cross-platform builds this does, the "push stuff to octopus" happens at the end in it's own job, which _only_ does those things. The git tagging happens in an earlier job which doesn't use OIDC and thus specifies nothing for permissions; The default permissions allow git tagging so we had no problem.
You can see a manual GHA run here:
https://github.com/OctopusDeploy/OctopusClients/actions/runs/7813217991
> GHA: Update setup-dotnet, use correct powershell date syntax

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/DeploymentFreezes/GetDeploymentFreezesResponse.cs
We don't publish any recent message contracts, so opting not to make this as IResponse. Otherwise we would use the message contract response.
> It's a response.. but not a IResponse

- source/Octopus.Server.Client/Model/MachinePolicyResource.cs
[SC-67117]
It is not removed, since it can be kept around for when talking to older Octopus servers.
relates to https://github.com/OctopusDeploy/Issues/issues/8578
> Mark PollingRequestMaximumMessageProcessingTimeout as Obsolete

- build/Build.cs
Stop the build from doing a restore as the Restore target runs first and is required.
> Stop the build from doing a restore

- source/Octopus.Client.Tests/Serialization/EndpointConverterFixture.cs
- source/Octopus.Client.Tests/Serialization/InheritedClassConverterFixture.cs
- source/Octopus.Client.Tests/Serialization/TentacleConfigurationConverterFixture.cs
- source/Octopus.Server.Client/Serialization/EndpointConverter.cs
- source/Octopus.Server.Client/Serialization/InheritedClassConverter.cs
[sc-71239]
The Kubernetes Agent resource couldn't actually be deserialized due to:
- No support for tiny types as the discriminator
- Incorrect resource type declaration
> Fix Kubernetes Agent resource serialization

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/BuiltInTasks.cs
We'd like to rename a task from `PollFeedsForTriggers` to `ProcessExternalFeedTriggers`. I'll do this in two parts in `OctopusClients` to avoid any chance of a breaking change.
[sc-76099]
> Change ProcessExternalFeedTriggers task name

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/BuiltInTasks.cs
Follow up to #839
Removes the now-unused `PollFeedsForTriggers` task
[sc-76099]
> Remove PollFeedsForTriggers task

- source/Octopus.Client.Tests/Model/TenantVariableResourceFixture.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Editors/Async/TenantVariablesEditor.cs
- source/Octopus.Server.Client/Editors/TenantVariablesEditor.cs
- source/Octopus.Server.Client/Model/TenantVariableResource.cs
Getting and setting tenant variable values using the client is difficult due to how they're accessed from the `TenantVariableResource`. It requires navigating 2 or 3 nested layers of dictionaries, with no indication of which keys are to be used at each level - you just have to know.
Also, the template being used is specified by its ID, which is not meaningful to end-users, rather than it's name. A lookup has to be manually performed each time to translate the name to the ID.
Added convenience methods to the `TenantVariablesResource` and `TenantVariableEditor` classes to simplify getting and setting values for tenant variables.
Example of usage in https://github.com/OctopusDeploy/OctopusDeploy/pull/24166
> Add helper methods for getting and setting tenant variables

- .nuke/build.schema.json
- source/Octopus.Client.Tests/Operations/RegisterMachineOperationFixture.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/EnvironmentResource.cs
- source/Octopus.Server.Client/Operations/IRegisterMachineOperation.cs
- source/Octopus.Server.Client/Operations/RegisterMachineOperation.cs
- source/Octopus.Server.Client/Operations/RegisterMachineOperationBase.cs
- source/Octopus.Server.Client/Operations/RegisterWorkerOperation.cs
- source/Octopus.Server.Client/Repositories/Async/BasicRepository.cs
- source/Octopus.Server.Client/Repositories/Async/EnvironmentRepository.cs
- source/Octopus.Server.Client/Repositories/Async/IFindBySlug.cs
- source/Octopus.Server.Client/Repositories/BasicRepository.cs
- source/Octopus.Server.Client/Repositories/EnvironmentRepository.cs
- source/Octopus.Server.Client/Repositories/IFindBySlug.cs
When registering a deployment target/machine, we currently require the environment names specified. This means that you can't supply an environment slug or id and have it correctly register.
To resolve this, I have added a new `Environments` property to `IRegisterMachineOperation` which can take either an environment name, slug or id and will search all options.
`EnvironmentNames` has been marked as obsolete.
We have kept the same logic around detecting missing `EnvironmentNames`. If there is an `EnvironmentNames` value that can't be found by name, we do not try and resolve that name to a slug or id, but throw an exception. We only check the slug and/or id for the new property
Shortcut story: [sc-77588]
Related to: https://github.com/OctopusDeploy/Issues/issues/8760
> Add ability to register machine to environments using slug or id

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/GeneratedAccessTokenResource.cs
- source/Octopus.Server.Client/Repositories/Async/UserRepository.cs
We need to generate an Access token for the helm chart in the E2E test in server, so I have put this in so we can do it via the Client.
Server change here: https://github.com/OctopusDeploy/OctopusDeploy/pull/24450
[sc-71113]
> Add GenerateAccessToken into UserRepository

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/MachineBasedResource.cs
There are a few tests in Server which use Octopus.Server.Client to create machines but they don't want background processes like HealthChecks to run. Adding this property allows us to skip the initial health check when adding a machine to make testing easier, more stable and decrease the load on the server running in the test.
In the Client all we have to do is add the additional property. The server PR (https://github.com/OctopusDeploy/OctopusDeploy/pull/24785) will handle this flag and ensure an initial health check isn't executed if the flag is true.
> Add SkipInitialHealthCheck flag to MachineBasedResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/TenantResource.cs
- source/Octopus.Server.Client/Operations/RegisterMachineOperation.cs
- source/Octopus.Server.Client/Repositories/TenantRepository.cs
Adding tenant slug support so that we can add tenant support to the Kubernetes agent helm chart
[sc-80799]
> Add Tenant slug support

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/DeploymentResource.cs
- source/Octopus.Server.Client/Model/PhaseProgressionResource.cs
- source/Octopus.Server.Client/Model/PhaseResource.cs
Adds priority-related fields to deployment resource and phase resources.
Note: `IsOptionalPhase` was missing in the client, which I've also added while adding the priority phase.
[sc-81662]
> Adds priority field to deployment resource and phases

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/DeploymentResource.cs
- source/Octopus.Server.Client/Model/PriorityMode.cs
Updates the priority field on a deployment resource from a boolean to an enum with three states: LifecycleDefault, On and Off, to ensure a priority of a deployment can inherit from a lifecycle if one isn't overriden from a deployment.
> Change priority field on deployment from a bool to an enum with three states.

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/MachineBasedResource.cs
- source/Octopus.Server.Client/Model/WorkerResource.cs
For some reason `MachineResource` was missing `SpaceId` which could lead to an error where machines would be added to the default space instead of the one specified.
> Add SpaceId to MachineResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Permission.cs
Adds permissions required to view/edit deployment targets tags.
Related to https://github.com/OctopusDeploy/OctopusDeploy/pull/24387
> Add target tag permissions

- source/Octopus.Client.Tests/Operations/RegisterKubernetesDeploymentTargetOperationFixture.cs
- source/Octopus.Client.Tests/Operations/RegisterKubernetesWorkerOperationFixture.cs
- source/Octopus.Client.Tests/Operations/RegisterMachineOperationFixture.cs
- source/Octopus.Client.Tests/Operations/RegisterWorkerOperationFixture.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Operations/IRegisterKubernetesClusterOperation.cs
- source/Octopus.Server.Client/Operations/IRegisterKubernetesDeploymentTargetOperation.cs
- source/Octopus.Server.Client/Operations/IRegisterKubernetesWorkerOperation.cs
- source/Octopus.Server.Client/Operations/IRegisterWorkerOperation.cs
- source/Octopus.Server.Client/Operations/RegisterKubernetesDeploymentTargetOperation.cs
- source/Octopus.Server.Client/Operations/RegisterKubernetesWorkerOperation.cs
- source/Octopus.Server.Client/Operations/RegisterMachineOperation.cs
- source/Octopus.Server.Client/Operations/RegisterWorkerOperation.cs
- source/Octopus.Server.Client/Repositories/Async/TenantRepository.cs
- source/Octopus.Server.Client/Repositories/Async/WorkerPoolRepository.cs
- source/Octopus.Server.Client/Repositories/WorkerPoolRepository.cs
- source/Octopus.Server.Client/Util/AsyncRepositoryExtensions.cs
- source/Octopus.Server.Client/Util/RepositoryExtensions.cs
We would like to support running the Kubernetes Agent as a worker. To do this, Tentacle must have a way to call the worker registration API of Octopus Server. It communicates with Server via Octopus.Client Operations, which act as an abstraction over the API library.
- [Helm chart](https://github.com/OctopusDeploy/helm-charts/pull/196)
- [Tentacle](https://github.com/OctopusDeploy/OctopusTentacle/pull/969)
[sc-82021]
- Introduces an `IRegisterKubernetesWorkerOperation`
- Deprecates the existing `IRegisterKubernetesClusterOperation` and rebrands it as `IRegisterKubernetesDeploymentTargetOperation` as we want to be clear in the distinction between the two (the functionality is still the same)
> Add client operations to support registering the Kubernetes agent as a worker

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/ProjectResource.cs
https://github.com/OctopusDeploy/OctopusClients/pull/859 introduced ProjectResource.AllowIgnoreChannelRules. This is an optional new field to allow users enable or disable bypassing of channel version rules (they are currently always able to be bypassed)
This feature is currently in early preview and all existing projects have this value set to true. If no value is provided in an API call, the value is not changed. If users update to this new version of the client and don't provide a value, the client will send false which may change the existing value.
To reduce the risk of existing users bringing in this unexpectedly changing the existing value, we're making this field nullable. We may change this again in the future, but this will be some other breaking change down the line.
> Make ProjectResource.AllowIgnoreChannelRules nullable

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/GitDependencyResource.cs
- source/Octopus.Server.Client/Model/SelectedGitResource.cs
We're adding support for non-primary Git dependencies: this PR adds client support for it.
The `GitResourceReferenceName` indicates whether or not it's a primary resource: no name makes it primary, specifying a name makes it non-primary.
See the equivalent property for Packages here: 
https://github.com/OctopusDeploy/OctopusClients/blob/f6d191220b086ebdc4c2684ed8e1296c790fffca/source/Octopus.Server.Client/Model/SelectedPackage.cs#L45
> Add support for multiple Git dependencies

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/PersistenceSettings.cs
This change added the RunbooksAreInGit property to the conversion state of projects.
As part of Project Git Runbooks we are currently updating the RunbookBuilder and RunbookProcessBuilder in the Octopus Deploy integration test library. The change to the builders will allow us  to quickly create Runbook test data, without needing to manually craft OCL. This change facilitates the builder being able to determine if it should be  an existing DB Runbook, or one of the new Git Runbooks.
> Add Runbooks are in Git to the Projects Conversion state

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/PackageReference.cs
We are adding support for setting package versions on a step in both deployment and Runbook processes. This adds this new field to the `PackageReference`. This feature is not available yet - any values set before the feature is enabled on your instance will be retained, but will be ignored when creating releases or running Runbooks.
> Add Version to PackageReference

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/HttpRouting/HttpRouteExtractor.cs
`OctopusAsyncClient` takes an `IHttpRouteExtractor` in its constructor, but the default implementation `HttpRouteExtractor` is not public.
Changing this class to public makes any inheritance of `OctopusAsyncClient` (and `HttpRouteExtractor` itself) much simpler.
Clones https://github.com/OctopusDeploy/OctopusClients/pull/871
[sc-91741]
> Change HttpRouteExtractor access modifier to public to match interface

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Accounts/Usages/AccountUsageResource.cs
Relates to https://github.com/OctopusDeploy/Issues/issues/5890
https://github.com/OctopusDeploy/OctopusDeploy/pull/28543 Updates the Account Usage Resource to include `ProjectTenantVariables` and `CommonTenantVariables`
The Octopus Client needs to also be updates to match for the OctopusClientVersusServerResources Tests.
> Update account usage resource to include tenant variables

- .github/workflows/main.yaml
[sc-96974]
GitHub are deprecating v3 of the `upload-artifact` and `download-artifact` actions.
This PR upgrades those actions to v4.
None of the breaking changes affect this repo.
[Deprecation notice: v3 of the artifact actions - GitHub Changelog](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)
> Upgrade artifact actions

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Permission.cs
Adds `PrioritizeTask` permission to control who can create prioritized deployments.
> Add prioritize task permission

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Editors/Async/GenericOidcAccountEditor.cs
- source/Octopus.Server.Client/Editors/GenericOidcAccountEditor.cs
- source/Octopus.Server.Client/Extensions/TypeExtensions.cs
- source/Octopus.Server.Client/Model/Accounts/AccountType.cs
- source/Octopus.Server.Client/Model/Accounts/GenericOidcAccountResource.cs
- source/Octopus.Server.Client/Model/VariableType.cs
- source/Octopus.Server.Client/Serialization/AccountConverter.cs
This change adds support for generic Oidc accounts to the client for [#project-generic-oidc](https://octopusdeploy.slack.com/archives/C081K9EPXT9)
> Adds Generic OIDC accounts

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/ModifyRunbookCommand.cs
- source/Octopus.Server.Client/Model/ModifyRunbookProcessCommand.cs
- source/Octopus.Server.Client/Model/RunbookRunGitParameters.cs
- source/Octopus.Server.Client/Model/RunbookRunGitResource.cs
- source/Octopus.Server.Client/Model/RunbookRunPreviewParameters.cs
- source/Octopus.Server.Client/Repositories/Async/RunbookProcessRepository.cs
- source/Octopus.Server.Client/Repositories/Async/RunbookRepository.cs
- source/Octopus.Server.Client/Repositories/Async/RunbookRunRepository.cs
Adds support for CaC Runbooks to the client library. The new CaC Runbook methods are not returned in links collections, so these methods are a little different to the older ones, and you now need to pass the Project resource, Git ref and slug to all of these new calls.
For now, we're only adding these new methods to the asynchronous repositories. We may expand these to the others eventually if there is enough demand for it.
The bulk of the changes are in the `RunbookRepository` and `RunbookProcessRepository` as this is where all of the new methods requiring Git references will live. 
You no longer need to create a snapshot and run directly when running a CaC Runbook. Instead just call the Run method for a given Git ref and slug, and the snapshot and run will be created in the background …
> Add Config as Code Runbooks support

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/SmtpConfigurationResource.cs
Update the SMTP configuration to include credential type and Google OAuth details for new Google SMTP OAuth 2.0 feature.
[sc-100819]
> Update SMTP Configuration with Google OAuth details

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/DebugMode.cs
- source/Octopus.Server.Client/Model/DeploymentResource.cs
- source/Octopus.Server.Client/Model/IExecutionResource.cs
- source/Octopus.Server.Client/Model/RunbookRunParameters.cs
- source/Octopus.Server.Client/Model/RunbookRunResource.cs
Adds the debug property to RunbookRun, Deployment and IExecution. This is part of work on [sc-100842](https://app.shortcut.com/octopusdeploy/story/100842/debug-checkbox-on-deployment-page) which adds support for a debug option on the create deployment and runbook run now layout pages. The field itself triggers the ExecutionManifest to contribute both the OctopusPrintVariables and OctopusPrintEvaluatedVariables properties as true.
> Add debug property to runbookruns deployments and execution resource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/TenantVariables/GetCommonVariablesByTenantIdRequest.cs
- source/Octopus.Server.Client/Model/TenantVariables/ModifyCommonVariablesByTenantIdCommand.cs
- source/Octopus.Server.Client/Model/TenantVariables/TenantCommonVariable.cs
- source/Octopus.Server.Client/Repositories/Async/TenantVariablesRepository.cs
- source/Octopus.Server.Client/Repositories/TenantVariablesRepository.cs
[SC-103509]
Required for: https://github.com/OctopusDeploy/OctopusDeploy/pull/31008
Previously, all templates were returned by the Get Tenant Variables endpoint which allowed Octopus UI and the Go CLI to find any missing/default values. When creating the new `api/{SpaceId}/tenants/{TenantId}/commonvariables` endpoint, we removed this functionality and only included templates for assigned variables. This PR adds a new array of missing and default variables to ensure that users can continue to access this data as required.
Default values are used for variables where a common variable template or project variable template has a default value set, but no value is explicitly set for one or more environment scopes.
Missing variables are similar to default variables, but are identified as having …
> Retrieve default/missing tenant common variables

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/TenantVariables/GetCommonVariablesByTenantIdRequest.cs
- source/Octopus.Server.Client/Model/TenantVariables/GetProjectVariablesByTenantIdRequest.cs
- source/Octopus.Server.Client/Model/TenantVariables/ModifyProjectVariablesByTenantIdCommand.cs
- source/Octopus.Server.Client/Model/TenantVariables/TenantProjectVariable.cs
- source/Octopus.Server.Client/Repositories/Async/TenantVariablesRepository.cs
- source/Octopus.Server.Client/Repositories/TenantVariablesRepository.cs
[SC-103510]
Previously, all templates were returned by the Get Tenant Variables endpoint which allowed Octopus UI and the Go CLI to find any missing/default values. When creating the new api/{SpaceId}/tenants/{TenantId}/projectvariables endpoint, we removed this functionality and only included templates for assigned variables. This PR adds a new array of missing and default variables to ensure that users can continue to access this data as required.
Default values are used for variables where a project variable template or project variable template has a default value set, but no value is explicitly set for one or more environment scopes.
Missing variables are similar to default variables, but are identified as having no default value for the template.
The new …
> Retrieve default/missing tenant project variables

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/TenantVariables/GetCommonVariablesByTenantIdRequest.cs
- source/Octopus.Server.Client/Model/TenantVariables/GetProjectVariablesByTenantIdRequest.cs
- source/Octopus.Server.Client/Model/TenantVariables/ModifyCommonVariablesByTenantIdCommand.cs
- source/Octopus.Server.Client/Model/TenantVariables/ModifyProjectVariablesByTenantIdCommand.cs
Relates to the changes in https://github.com/OctopusDeploy/OctopusDeploy/pull/30991
> Rename tenant variable property

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/OctopusAsyncClient.cs
- source/Octopus.Server.Client/OctopusClient.cs
- source/Octopus.Server.Client/OctopusClientOptions.cs
This adds a semaphore around the request sending for both the sync and async client. This is used to limit the number of requests that are made so that you don't DOS the Octopus Server.
The [alternate](https://github.com/OctopusDeploy/OctopusClients/pull/912) was rejected as it didn't apply to sync client and 
HTTP/2
I manually tested both clients and changing the value affects the duration of the requests.
I tested it out against our internal server and when limited to 30 connections it's almost as fast as when it's 100, showing limited benefit from increased parallelism.
> Added semaphore to control number of requests

- .github/dependabot.yml
- .github/workflows/main.yaml
Added dependabot to check github actions and pinned third party actions, have left the default github and the internal actions.
Dependabot will now run weekly for this repo and check the github actions for updates
Also updated dorny/test-reporter to v2, and pinned release.
Before Merge:
> 🧹 Added dependabot and implemented hash pinning for third party actions

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/AwsElasticContainerRegistryFeedResource.cs
Adds UseMachineCredentials to AWS ECR feeds to support using worker credentials to authenticate.
[sc-104095]
> Add UseMachineCredentials for ECR feeds

- source/Octopus.Server.Client/Model/DeploymentFreezes/CreateDeploymentFreezeCommand.cs
- source/Octopus.Server.Client/Model/DeploymentFreezes/CreateDeploymentFreezeResponse.cs
- source/Octopus.Server.Client/Model/DeploymentFreezes/GetDeploymentFreezeByIdResponse.cs
- source/Octopus.Server.Client/Model/DeploymentFreezes/GetDeploymentFreezesRequest.cs
- source/Octopus.Server.Client/Model/DeploymentFreezes/GetDeploymentFreezesResponse.cs
- source/Octopus.Server.Client/Model/DeploymentFreezes/ModifyDeploymentFreezeCommand.cs
- source/Octopus.Server.Client/Model/DeploymentFreezes/ModifyDeploymentFreezeResponse.cs
Unless this was an intentional inclusion, but since none of the other contracts have the Optional attribute (that is currently a server side concern), it looks like it wasn't. 
This will let us remove the `Octopus.Server.MessageContracts.Base` dependency.
> Remove `Optional` attribute from Deployment Freezes

- build/Build.cs
- source/Octopus.Client.E2ETests/InlinedDependenciesFixture.cs
- source/Octopus.Server.Client/Octopus.Server.Client.csproj
It is no longer used by anything in the client.
The `Octopus.Client` assembly uses IL Inlining so that it can be standalone (`Octopus.Server.Client` does not).
I used dotPeak to compare this branch built assembly against the current release version and found the expected  differences:
> Remove the `Octopus.Server.MessageContracts.Base` reference 

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/DeploymentResource.cs
- source/Octopus.Server.Client/Model/DeploymentSettingsResource.cs
- source/Octopus.Server.Client/Model/RunbookResource.cs
- source/Octopus.Server.Client/Model/RunbookRunResource.cs
[sc-96575]
Related to https://github.com/OctopusDeploy/OctopusDeploy/pull/34350
> FailTargetDiscovery on deployment settings and runbook run
