- source/OctopusTools/Commands/PackageVersionResolver.cs
Version arg expects step name, not packageid
> Fixed incorrect error message.  

- source/OctopusTools.Tests/OctopusTools.Tests.csproj
- source/OctopusTools.Tests/packages.config
- source/OctopusTools/Commands/DeployReleaseCommand.cs
- source/OctopusTools/OctopusTools.csproj
- source/OctopusTools/packages.config
Also updated Octopus.Client to latest version (3.2.9)
Fixes OctopusDeploy/Issues#2235
> Add channel option to the deploy-release command to allow deploying the latest release in a channel

- source/OctopusTools.Tests/Commands/ListEnvironmentsCommandFixture.cs
- source/OctopusTools.Tests/Commands/ListMachinesCommandFixture.cs
- source/OctopusTools.Tests/OctopusTools.Tests.csproj
- source/OctopusTools/Commands/ListEnvironmentsCommand.cs
- source/OctopusTools/Commands/ListMachinesCommand.cs
- source/OctopusTools/OctopusTools.csproj
New list-machines Command accepts the following parameters:
--environment="environment name"
--status="[Online, Offline, Unknown, NeedsUpgrade...]"
> Add list-machines Command

- source/OctopusTools/Commands/ApiCommand.cs
- source/OctopusTools/Commands/CreateReleaseCommand.cs
- source/OctopusTools/Diagnostics/LogExtensions.cs
May need to squash the commits?
> Feature vstslog

- source/Octopus.Cli/Commands/ProjectExport.cs
- source/Octopus.Cli/Exporters/ProjectExporter.cs
- source/Octopus.Cli/Importers/ProjectImporter.cs
- source/Octopus.Cli/Octopus.Cli.csproj
- source/Octopus.Cli/packages.config
> Export and import project channels

- source/Octo/Commands/DeployReleaseCommand.cs
- source/Octo/Commands/PromoteReleaseCommand.cs
Add the `--updateVariables` option to update a release's variable snapshot.
```
Handshaking with Octopus server: http://localhost:8065
Handshake successful. Octopus version: 0.0.0-local; API version: 3.0.0
GET http://localhost:8065/api/users/me
Authenticated as: admin <null>
Finding project: Updating release variables
GET http://localhost:8065/api/projects
Finding release 0.0.3
GET http://localhost:8065/api/projects/Projects-141/releases/0.0.3
Updating the release variable snapshot with variables from the project
```
Fixes #102
> Add option to update release variables when deploying or promoting a release

- source/Octopus.Client/OctopusRepository.cs
- source/Octopus.Client/Repositories/Async/IProjectRepository.cs
- source/Octopus.Client/Repositories/Async/ProjectsRepository.cs
- source/Octopus.Client/Repositories/Async/TaskRepository.cs
- source/Octopus.Client/Repositories/IProjectRepository.cs
- source/Octopus.Client/Repositories/ITaskRepository.cs
Added method for gathering all Releases related to project, rather than having to page through them.
Added method for gathering the Tasks that a Task currently is queued behind.
> Project and Task Enhancements

- global.json
fixes #113, fix usage on VS 2015 / cmdline when VS 2017 RC is installed
> lock this project to dotnet preview2 sdk

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/DeploymentStepCondition.cs
This adds a "Variable" option to our DeploymentStepProperties model
> Adding variable run condition

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/DeploymentResource.cs
- source/Octopus.Client/Model/TaskResource.cs
Relates to OctopusDeploy/Issues#2856
> Add queue time expiry to deployment resource

- source/Octo/Commands/ApiCommand.cs
Fixes OctopusDeploy/Issues#2868
> Add a timeout option to Octo

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ProjectConnectivityPolicy.cs
Relates to OctopusDeploy/Issues#2732
> Added AllowDeploymentsToNoTargets to ProjectConnectivityPolicy

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/EventNotificationSubscription.cs
- source/Octopus.Client/Repositories/Async/EventRepository.cs
- source/Octopus.Client/Repositories/EventRepository.cs
Updating event repositories to use new autoId properties
> Updating event repositories to use new autoId properties

- source/Octo/Commands/ApiCommand.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/OctopusAsyncClient.cs
- source/Octopus.Client/OctopusClientOptions.cs
- source/Octopus.Client/Util/ClientProxy.cs
Resolves https://github.com/OctopusDeploy/Issues/issues/3043
> Added proxy support to Octo.exe and Octopus.Client

- source/Octo.Tests/Commands/ListDeploymentsCommandFixture.cs
- source/Octo/Commands/ListDeploymentsCommand.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.cs
- source/Octopus.Client/Repositories/Async/DeploymentRepository.cs
- source/Octopus.Client/Repositories/DeploymentRepository.cs
Fix for:  https://github.com/OctopusDeploy/Issues/issues/3024
> list-deployments action, as list-latestdeployments was limited

- source/Octopus.Client.Tests/Operations/RegisterMachineOperationFixture.cs
- source/Octopus.Client/Operations/RegisterMachineOperation.cs
Relates to OctopusDeploy/Issues#2955
> Helpful error messages for register machine

- source/Octo/Importers/ProjectImporter.cs
Attempting to resolve http://help.octopusdeploy.com/discussions/problems/51563
> Gracefully handle missing ARC channel when importing project

- source/Octopus.Client.Tests/Operations/RegisterMachineOperationFixture.cs
- source/Octopus.Client/Operations/RegisterMachineOperation.cs
It will be set to the default on the server side if its a new machine.
> Dont overwrite machine policy if not passed

- source/Octopus.Client.Tests/Integration/OctopusClient/UserAgentTests.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Extensions/AssemblyExtensions.cs
- source/Octopus.Client/Model/ApiConstants.cs
- source/Octopus.Client/OctopusAsyncClient.cs
- source/Octopus.Client/OctopusClient.cs
Relates to https://github.com/OctopusDeploy/Issues/issues/3359
> Send User-Agent info with HTTP requests

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.cs
- source/Octopus.Client.Tests/project.json
- source/Octopus.Client/Model/ProjectResource.cs
Just added property.. The config change was just a re-sort
> Project dash

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/IHttpOctopusClient.cs
- source/Octopus.Client/Model/FeaturesConfigurationResource.cs
- source/Octopus.Client/OctopusAsyncClient.cs
- source/Octopus.Client/OctopusClient.cs
Added `IsBrowserCachingEnabled ` to `FeaturesConfigurationResource`. Also added `AfterReceivingHttpResponse` to `IOctopusClient` to enable testing
> Overalldash

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/TeamResource.cs
- source/Octopus.Client/Model/UserPermissionRestriction.cs
Related to OctopusDeploy/OctopusDeploy#1003
> Add missing field for project group ids

- source/Octo.Tests/Commands/ListDeploymentsCommandFixture.cs
- source/Octo/Commands/ListDeploymentsCommand.cs
Fixes: https://github.com/OctopusDeploy/Issues/issues/3403
> check multi-tenant feature is on before trying to load them

- source/Octo/Commands/CreateReleaseCommand.cs
Fixes https://github.com/OctopusDeploy/Issues/issues/3056
> Added info about support for markdown

- source/Octo/Commands/DeploymentCommandBase.cs
https://octopusdeploy.slack.com/archives/C3KT1DFSM/p1492542209330225
> Updated the deployment creation failure message.

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Operations/IRegisterMachineOperation.cs
- source/Octopus.Client/Operations/RegisterMachineOperation.cs
> Add overloads that take interfaces

- source/Octopus.Client.Tests/Octopus.Client.Tests.csproj
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Repositories/Async/DeploymentRepository.cs
- source/Octopus.Client/Repositories/Async/EventRepository.cs
- source/Octopus.Client/Repositories/Async/InterruptionRepository.cs
- source/Octopus.Client/Repositories/Async/ProjectRepository.cs
- source/Octopus.Client/Repositories/Async/ReleaseRepository.cs
- source/Octopus.Client/Repositories/Async/TaskRepository.cs
- source/Octopus.Client/Repositories/Async/TenantRepository.cs
- source/Octopus.Client/Repositories/DeploymentRepository.cs
- source/Octopus.Client/Repositories/EventRepository.cs
- source/Octopus.Client/Repositories/IPaginate.cs
- source/Octopus.Client/Repositories/ProjectRepository.cs
- source/Octopus.Client/Repositories/ReleaseRepository.cs
- source/Octopus.Client/Repositories/TaskRepository.cs
- source/Octopus.Client/Repositories/TenantRepository.cs
- source/Octopus.Client/Repositories/nterruptionRepository.cs
This will be supported in Server 3.14.159
Related to https://github.com/OctopusDeploy/Issues/issues/3572
> Added support for the take parameter

- source/Octo.Tests/Commands/DeployReleaseCommandTestFixture.cs
- source/Octo.Tests/Octo.Tests.csproj
- source/Octo/Commands/DeploymentCommandBase.cs
- source/Octopus.Client.Tests/Conventions/RepositorySymetryConventions.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client.Tests/Repositories/Async/TaskRepositoryTests.cs
- source/Octopus.Client/Repositories/Async/TaskRepository.cs
- source/Octopus.Client/Repositories/TaskRepository.cs
from Octo to WaitForCompletion. Fixes https://github.com/OctopusDeploy/OctopusClients/issues/180
> Passed a timespan instead of an integer number of minutes

- source/Octo/Commands/CreateReleaseCommand.cs
- source/Octo/Commands/DeployReleaseCommand.cs
- source/Octo/Commands/DeploymentCommandBase.cs
Fixes https://github.com/OctopusDeploy/OctopusClients/issues/181
> Set the defaults for Promote Release command. 

- source/Octopus.Client/OctopusAsyncClient.cs
I've inherited from NuGetFeedResource to add the property to verify that it works & allows the 'Use extended API' option to be modified. 
https://github.com/paulmarsy/OctopusNuGetDeploymentFeed/blob/3aa99d370529a6a5b533a8ce771a6d192aaeb0aa/OctopusNuGetDeploymentFeed/Octopus/EnhancedNuGetFeedResource.cs
> Adding 'EnhancedMode' NuGet feed resource property

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Operations/IRegisterMachineOperation.cs
- source/Octopus.Client/Operations/RegisterMachineOperation.cs
relates to https://github.com/OctopusDeploy/Issues/issues/3815
> Add option to set a proxy in RegisterMachineOperation

- source/Octo/Commands/CreateReleaseCommand.cs
- source/Octo/Commands/ReleasePlan.cs
- source/Octo/Commands/ReleasePlanBuilder.cs
- source/Octo/Commands/ReleasePlanItem.cs
Fixes https://github.com/OctopusDeploy/Issues/issues/3867
> Fixed checks for viable release with script only steps

- source/Octo.Tests/Diagnostics/LogUtilitiesFixture.cs
- source/Octo/Commands/ApiCommand.cs
- source/Octo/Commands/PackCommand.cs
- source/Octo/Diagnostics/LogUtilities.cs
- source/Octo/Program.cs
This is a proposal for fixing #120.
I'm not very familiar with your code base, so I apologize if it there are discrepancies in code style or similar. I've tried to keep the code as idiomatic to the one in the code base.
If you have any feedback for changes and/or improvements I will happily change my code. : smile:
> Added log level option to commands.

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ProjectedTeamReferenceDataItem.cs
- source/Octopus.Client/Model/UserPermissionSetResource.cs
This PR adds additional fields provided by the user permissions API as part of the work done for https://github.com/OctopusDeploy/Issues/issues/3889
> Update user permissions response

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/EventNotificationSubscription.cs
Relates to OctopusDeploy/Issues#3892
> Add webhook timeout to subscriptions

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/DeploymentStepPackageRequirement.cs
- source/Octopus.Client/Model/DeploymentStepResource.cs
Adds `PackageRequirement` to `DeploymentStep`
Relates to OctopusDeploy/Issues#3974
> Explicit configuration of when a step should run wrt package acqusition

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/Permission.cs
Fixes OctopusDeploy/Issues#4217
Server change OctopusDeploy/OctopusDeploy#1807
> Added FeedEdit permission

- .gitignore
- source/Octo.Tests/Commands/VersionTestFixture.cs
- source/Octo.Tests/Octo.Tests.csproj
- source/Octo/Commands/VersionCommand.cs
Basic `octo.exe version` command. Simply returns the version number.
> Added version command (plus test)

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/BuiltInTasks.cs
- source/Octopus.Client/Model/Migrations/MigrationImportResource.cs
- source/Octopus.Client/Model/Migrations/MigrationPartialExportResource.cs
- source/Octopus.Client/Repositories/Async/MigrationRepository.cs
- source/Octopus.Client/Repositories/MigrationRepository.cs
Refactoring out the term 'Space' as this was intended for ODCM only and added migration builtin tasks so we can create these tasks via OctopusClients
> Updates to migration APIs

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/DeploymentActionResource.cs
Corresponds to https://github.com/OctopusDeploy/OctopusDeploy/pull/1988
> Added IsRequired property to DeploymentAction

- source/Octo.Tests/Commands/ApiCommandFixture.cs
- source/Octopus.Cli/Commands/ApiCommand.cs
Fixes https://github.com/OctopusDeploy/OctopusClients/issues/225
> Enh envvars 225

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/DefaultLinkResolver.cs
- source/Octopus.Client/ILinkResolver.cs
- source/Octopus.Client/IOctopusAsyncClient.cs
- source/Octopus.Client/IOctopusClient.cs
- source/Octopus.Client/Model/LoginCommand.cs
- source/Octopus.Client/Model/LoginState.cs
- source/Octopus.Client/OctopusAsyncClient.cs
- source/Octopus.Client/OctopusClient.cs
- source/Octopus.Client/OctopusServerEndpoint.cs
- source/Octopus.Client/Repositories/Async/UserRepository.cs
- source/Octopus.Client/Repositories/UserRepository.cs
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/2029
> Handle SSL Offloading for Auth Cookies

- source/Octo.Tests/Commands/CleanWorkerPoolCommandFixture.cs
- source/Octo.Tests/Commands/CreateWorkerPoolCommandFixture.cs
- source/Octo.Tests/Commands/ListWorkerMachinesCommandFixture.cs
- source/Octo.Tests/Commands/ListWorkerPoolsCommandFixture.cs
- source/Octopus.Cli/Commands/Machine/ListWorkerMachinesCommand.cs
- source/Octopus.Cli/Commands/WorkerPool/CleanWorkerPoolCommand.cs
- source/Octopus.Cli/Commands/WorkerPool/CreateWorkerPoolCommand.cs
- source/Octopus.Cli/Commands/WorkerPool/ListWorkerPoolsCommand.cs
Patterned off similar endpoints for Environments and Machines.
> Add workers to Octo

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/OctopusServerNodeResource.cs
Relates to OctopusDeploy/Issues#4540
> Add heartbeat policy to nodes

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/VariablePromptOptions.cs
Added DisplaySettings property to VariablePromptOptions.
Corresponds with https://github.com/OctopusDeploy/OctopusDeploy/pull/2407
See https://github.com/OctopusDeploy/Issues/issues/4531
> Prompted Variable Control Types

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ScheduledTaskDetailsResource.cs
- source/Octopus.Client/Octopus.Client.csproj
- source/Octopus.Client/Repositories/Async/SchedulerRepository.cs
- source/Octopus.Client/Repositories/SchedulerRepository.cs
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/2578
> Add log endpoints to ISchedulerRepository

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Repositories/Async/MachinePolicyRepository.cs
- source/Octopus.Client/Repositories/MachinePolicyRepository.cs
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/2582
> Add GetMachines to IMachinePolicyRepository

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Repositories/Async/CertificateConfigurationRepository.cs
- source/Octopus.Client/Repositories/CertificateConfigurationRepository.cs
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/2576
> Add GetPublicCertificate to CertificateConfigurationRepository

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Features/DeltaCompression.cs
- source/Octopus.Client/Model/PackageSignatureResource.cs
- source/Octopus.Client/Octopus.Client.csproj
- source/Octopus.Client/Repositories/Async/BuiltInPackageRepositoryRepository.cs
- source/Octopus.Client/Repositories/BuiltInPackageRepositoryRepository.cs
- source/Octopus.Client/Util/PackageIdentityParser.cs
- source/Octopus.Client/Util/TemporaryFile.cs
Added delta compression to BuiltInPackageRepositoryRepository and consequently to `Octo.exe`. Closes https://github.com/OctopusDeploy/Issues/issues/4833
> Added delta compression

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/IOctopusAsyncRepository.cs
- source/Octopus.Client/IOctopusRepository.cs
- source/Octopus.Client/Model/UserPermissionRestriction.cs
- source/Octopus.Client/OctopusAsyncRepository.cs
- source/Octopus.Client/OctopusRepository.cs
- source/Octopus.Client/Repositories/Async/EventRepository.cs
- source/Octopus.Client/Repositories/Async/MixedScopeBaseRepository.cs
- source/Octopus.Client/Repositories/Async/ScopedUserRoleRepository.cs
- source/Octopus.Client/Repositories/Async/SubscriptionRepository.cs
- source/Octopus.Client/Repositories/Async/TaskRepository.cs
- source/Octopus.Client/Repositories/Async/TeamsRepository.cs
- source/Octopus.Client/Repositories/Async/UserPermissionsRepository.cs
- source/Octopus.Client/Repositories/Async/UserRepository.cs
- source/Octopus.Client/Repositories/EventRepository.cs
- source/Octopus.Client/Repositories/MixedScopeBaseRepository.cs
- source/Octopus.Client/Repositories/ScopedUserRoleRepository.cs
- source/Octopus.Client/Repositories/SubscriptionRepository.cs
- source/Octopus.Client/Repositories/TaskRepository.cs
- source/Octopus.Client/Repositories/TeamsRepository.cs
- source/Octopus.Client/Repositories/UserPermissionsRepository.cs
- source/Octopus.Client/Repositories/UserRepository.cs
- source/Octopus.Client/Util/SpaceQueryContext.cs
Client side changes for user permissions
> User permissions in Spaces

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Editors/Async/ProjectEditor.cs
- source/Octopus.Client/Editors/ProjectEditor.cs
- source/Octopus.Client/Repositories/Async/ProjectRepository.cs
- source/Octopus.Client/Repositories/ProjectRepository.cs
Our API expects a "clone" query string parameter when cloning projects. Adding the ability for that to happen so we can write tests around cloning.
> Add ability to clone a project

- source/Octopus.Cli/Commands/Deployment/DeploymentCommandBase.cs
Fixes OctopusDeploy/Issues#5033
> Add parameter to exclude machines from a deployment

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Editors/Async/AzureServicePrincipalAccountEditor.cs
- source/Octopus.Client/Editors/Async/AzureSubscriptionAccountEditor.cs
- source/Octopus.Client/Editors/AzureServicePrincipalAccountEditor.cs
- source/Octopus.Client/Editors/AzureSubscriptionAccountEditor.cs
- source/Octopus.Client/Model/Accounts/AzureServicePrincipalAccountResource.cs
- source/Octopus.Client/Model/Accounts/AzureSubscriptionAccountResource.cs
- source/Octopus.Client/Model/Endpoints/AzureWebAppEndpointResource.cs
Fixes OctopusDeploy/OctopusClients#365
Fixed inconsistent interface in editor between Service Principal and Management Cert accounts
Fixed missing setter on WebSite Name property
> Support for Azure Web Slot endpoint

- source/Octo.Tests/Commands/ApiCommandFixtureBase.cs
- source/Octopus.Cli/Commands/ApiCommand.cs
Better error messages when default space is off
> Handling when we are running against an old Server

- source/Octopus.Client/Model/Migrations/MigrationImportResource.cs
- source/Octopus.Client/Model/Migrations/MigrationPartialExportResource.cs
SpaceId for source
other for destination
> SpaceId and DestinationSpaceId properties for MigrationPartialExportResource

- source/Octo.Tests/Commands/ApiCommandFixtureBase.cs
- source/Octo.Tests/Commands/CreateReleaseCommandFixture.cs
- source/Octopus.Cli/Commands/Deployment/DeploymentCommandBase.cs
- source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs
Fixes https://github.com/OctopusDeploy/Issues/issues/5329
> Create release and deploy validation

- source/Octo.Tests/Commands/ApiCommandFixtureBase.cs
- source/Octo.Tests/Commands/CreateReleaseCommandFixture.cs
- source/Octopus.Cli/Commands/Deployment/DeploymentCommandBase.cs
- source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs
Reverts OctopusDeploy/OctopusClients#395
> Revert "Create release and deploy validation"

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/TaskResourceCollection.cs
- source/Octopus.Client/Repositories/Async/BasicRepository.cs
- source/Octopus.Client/Repositories/Async/TaskRepository.cs
- source/Octopus.Client/Repositories/Async/UserRepository.cs
- source/Octopus.Client/Repositories/BasicRepository.cs
- source/Octopus.Client/Repositories/TaskRepository.cs
- source/Octopus.Client/Repositories/UserRepository.cs
Added `GetActiveWithSummary` and `GetAllWithSummary` to `TaskRepository` as well as `UserRepository.FindByUsername`
> Helper methods to Tasks and Users

- source/Octopus.Client/Repositories/Async/PackageMetadataRepository.cs
- source/Octopus.Client/Repositories/PackageMetadataRepository.cs
Fixes https://trello.com/c/0xULFGKG/56-pushing-metadata-ignores-your-space-selection
> Fix package metadata links

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/EventNotificationSubscription.cs
- source/Octopus.Client/Repositories/Async/EventRepository.cs
- source/Octopus.Client/Repositories/EventRepository.cs
Supporting PR for https://github.com/OctopusDeploy/OctopusDeploy/pull/3650
> Enh subscription project groups

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/OctopusServerNodeResource.cs
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/3546
> Enh nodesettings

- source/Octopus.Client/Repositories/BasicRepository.cs
Provides some clearer advice when misusing the Client to modify out of scope resources.
[Internal kanban](https://trello.com/c/qEBhmQm7/236-add-validation-to-octopusclient-when-the-spaceid-from-the-route-does-not-match-the-one-from-the-resource-and-throw-exception-if)
> Adds check for spaceId when modifying resources

- source/Octopus.Client/Repositories/BasicRepository.cs
Spotted some issues in Server that I hadn't considered
Reverts OctopusDeploy/OctopusClients#409
> Revert "Adds check for spaceId when modifying resources"

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ActionTemplateCategoryResource.cs
- source/Octopus.Client/Model/ActionTemplateSearchResource.cs
- source/Octopus.Client/Repositories/ActionTemplateRepository.cs
- source/Octopus.Client/Repositories/Async/ActionTemplateRepository.cs
Related to https://github.com/OctopusDeploy/OctopusDeploy/pull/3588
> Adding step template categories

- source/Octopus.Cli/Commands/Releases/ReleasePlan.cs
> Add null reference check to cover case when calling older server

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/PackageBuildMetadata.cs
- source/Octopus.Client/Model/ReleaseChanges.cs
Relates to OctopusDeploy/Issues#5583
> Include Package Build Metadata in the deployment variables

- source/Octopus.Client/Repositories/Async/WorkerRepository.cs
- source/Octopus.Client/Repositories/WorkerRepository.cs
does not use correct endpoint for worker discovery
> correct worker discover endpoint

- source/Octopus.Client.Tests/Integration/OctopusClient/TimeoutTests.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/OctopusAsyncClient.cs
- source/Octopus.Client/Repositories/Async/BuiltInPackageRepositoryRepository.cs
- source/Octopus.Client/Repositories/BuiltInPackageRepositoryRepository.cs
Relates to https://github.com/OctopusDeploy/Issues/issues/5585
> Add overload to allow disabling delta compression on package push

- source/Octopus.Client/Repositories/Async/BuiltInPackageRepositoryRepository.cs
- source/Octopus.Client/Repositories/BuiltInPackageRepositoryRepository.cs
> fix OverwriteModeLink.Link strings and if/else order

- source/Octopus.Client/Operations/RegisterMachineOperation.cs
Update machine registration failure message to reflect actual name uniqueness rule
> Duplicate machine message

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/MachineHealthCheckPolicy.cs
Related to https://github.com/OctopusDeploy/Issues/issues/5713
> Added cron options to MachineHealthCheckPolicy

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/PackageMetadata/OctopusPackageMetadataMappedResource.cs
To match message field added to Server in OctopusDeploy/OctopusDeploy#4060
> support OctopusPackageMetadataMappedResource.IncompleteDataWarning

- source/Octopus.Client/Model/ChannelResource.cs
- source/Octopus.Client/Repositories/Async/ChannelRepository.cs
This was originally a PR from https://github.com/OctopusDeploy/OctopusClients/pull/297/files. It has been tidied up slightly for consistency.
> Get releases for a specific channel

- source/Octopus.Client/Octopus.Client.csproj
Quick PR to update links for PackageProjectUrl and PackageLicenseUrl
> Update nuspec links

- source/Octopus.Client/Octopus.Client.nuspec
As it wasn't working in a new c# netcore project
> Re-add netcore deps

- build.cake
- source/Octopus.Client.E2ETests/AssemblyExtensions.cs
- source/Octopus.Client.E2ETests/InlinedDependenciesFixture.cs
- source/Octopus.Client.E2ETests/NuSpecDependenciesFixture.cs
- source/Octopus.Client.E2ETests/Octopus.Client.E2ETests.csproj
- source/Octopus.Client.E2ETests/PowerShellExecutionFixture.cs
- source/Octopus.Client.E2ETests/SilentProcessRunner.cs
- source/Octopus.Client.E2ETests/TestHelpers.cs
- source/Octopus.Client/Extensions/AssemblyExtensions.cs
- source/Octopus.Client/Octopus.Client.nuspec
- source/OctopusClient.sln
Make sure the packed, ilmerged dll we're going to ship actually works the way we expect it to - ie, dependencies are correct etc
> Add tests to ensure the packed, ilmerged artifacts work

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/SmtpConfigurationResource.cs
This new prop was added to `SmtpConfigurationResource` in   https://github.com/OctopusDeploy/OctopusDeploy/pull/4361
Need to add it in this project as well
> adding Timeout prop to SmtpConfigurationResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/TeamResource.cs
> add description to team resource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ProjectReference.cs
- source/Octopus.Client/Model/UserResource.cs
Add ProjectReference and recent projects property to UserResource
> add recent projects to user resource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ProjectReference.cs
add new field to project reference
> add AccessCount to projectReference

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/UserResource.cs
convert recently viewed field mutable as it always returns null
> make recently viewed mutable

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/RunbookResource.cs
Server changes: https://github.com/OctopusDeploy/OctopusDeploy/pull/4844
> Add connectivity policy to runbooks

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/Accounts/Usages/AccountUsageResource.cs
- source/Octopus.Client/Model/LibraryVariableSetResource.cs
- source/Octopus.Client/Repositories/Async/BasicRepository.cs
- source/Octopus.Client/Repositories/BasicRepository.cs
This PR adds the resource changes needed for runbook related usage information
> Add runbook resource usage changes accounts and library variablesets

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/RunbookResource.cs
Server PR: https://github.com/OctopusDeploy/OctopusDeploy/pull/4849
> Add separate multi-tenancy settings to runbooks

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/DashboardProjectResource.cs
Server PR: https://github.com/OctopusDeploy/OctopusDeploy/pull/4875
> Pass TenantedDeploymentMode to the client properly, to allow the dashboard to decide if project deployments are multi-tenanted

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/SummaryResource.cs
- source/Octopus.Client/Model/SummaryResourcesCombined.cs
Update `SummaryResource` and `SummaryResourcesCombined` to support `MachineIdsForTentacleUpgrade`
> Add MachineIdsForTentacleUpgrade to Resource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/Triggers/ScheduledTriggers/ContinuousDailyScheduledTriggerFilterResource.cs
This is a PR to change the RunAfter and RunUntil DateTime properties to be non nullable,
> Change Continuous daily trigger to have non optional RunAfter RunUntil times 

- source/Octopus.Client/Repositories/Async/ProjectTriggerRepository.cs
- source/Octopus.Client/Repositories/ProjectTriggerRepository.cs
merge just before we tag
TODO: nick can we have more whitelist so this can merge earlier?
> 2019.11 bump

- source/Octopus.Client/Octopus.Client.nuspec
We were previously pointing to the pricing page?
> Point to apache 2 license file in repo

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/BuiltInTasks.cs
- source/Octopus.Client/Repositories/Async/BasicRepository.cs
- source/Octopus.Client/Repositories/Async/TaskRepository.cs
- source/Octopus.Client/Repositories/BasicRepository.cs
- source/Octopus.Client/Repositories/TaskRepository.cs
Needed for e2e tests on the server.
> Add support for script console run on server

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/DeploymentActionResource.cs
- source/Octopus.Client/Model/VariableType.cs
Related to https://github.com/OctopusDeploy/OctopusDeploy/pull/5107
> Added WorkerPoolVariable property to DeploymentActionResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/LicenseStatusResource.cs
To bring it into sync with the server.
I think this can go out as a patch - happy to hear your thoughts on this.
> Add missing fields to LicenseStatusResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/DocumentTypeResource.cs
- source/Octopus.Client/Model/EventAgentResource.cs
- source/Octopus.Client/Model/EventCategoryResource.cs
- source/Octopus.Client/Model/EventGroupResource.cs
- source/Octopus.Client/Repositories/Async/EventRepository.cs
- source/Octopus.Client/Repositories/EventRepository.cs
Part of a push to get Client and Server resources back in sync
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/5383
> Add support for DocumentTypes, EventAgents, EventGroups & EventCategories

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/DeploymentActionContainer.cs
- source/Octopus.Client/Model/DeploymentActionResource.cs
Add DeploymentActionResource changes to client 
Internal link:
https://trello.com/c/wTwsfSzu/21-investigate-process-model-changes
> Action Container Images Model Changes

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/DeploymentActionContainer.cs
- source/Octopus.Client/Model/DeploymentActionResource.cs
Reverts OctopusDeploy/OctopusClients#516
> Revert "Action Container Images Model Changes"

- source/Octopus.Client/Features/DeltaCompression.cs
> Fixed typo

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/DeploymentActionCondition.cs
- source/Octopus.Client/Model/DeploymentActionResource.cs
This PR adds the resources and enums required for child run conditions.
> Add child run conditions

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/FeaturesConfigurationResource.cs
Adds the IsConfigurationAsCode to our feature configuration
> Adding config as code feature flag

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ProjectResource.cs
- source/Octopus.Client/Model/VersionControlSettingsResource.cs
Adds the properties needed to configure a project as Config as Code
> Add Version Control Settings for configuration as code

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/DashboardItemResource.cs
- source/Octopus.Client/Repositories/Async/DashboardRepository.cs
- source/Octopus.Client/Repositories/DashboardRepository.cs
Add `includePrevious` arg to dashboard repository dynamic dashboard
Related: 
https://github.com/OctopusDeploy/OctopusCLI/pull/94
https://github.com/OctopusDeploy/OctopusCLI/pull/94
> Add includePrevious arg to dashboard repository dynamic dashboard

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/ReleaseResource.cs
fixing the name of VersionControlReference
> update name of VersionControlReference on release

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/SpaceSearchResult.cs
- source/Octopus.Client/Repositories/Async/SpaceRepository.cs
- source/Octopus.Client/Repositories/SpaceRepository.cs
Client PR for the corresponding [server PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/7854) to enable global search within a space.
> Adding new space search endpoints

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/RetentionDefaultConfigurationResource.cs
Client resource for this [Server PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/8589)
> Expose new RetentionDefaultConfigurationResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client/Model/Endpoints/KubernetesEndpointResource.cs
- source/Octopus.Client/Model/Endpoints/KubernetesPodServiceAuthenticationResource.cs
- source/Octopus.Client/Model/MultipleAccountType.cs
- source/Octopus.Client/Serialization/EndpointWithMultipleAuthenticationConverter.cs
Updated and added resource classes to match with Core classes.
- Updated `KubernetesEndpointResource.cs` => added `ClusterCertificatePath` field
- Added `KubernetesPodServiceAuthenticationResource`
OctopusDeploy PR: https://github.com/OctopusDeploy/OctopusDeploy/pull/8637
> Added: Kubernetes resource classes

- source/Octopus.Server.Client/Repositories/Async/DeploymentSettingsRepository.cs
Fixed a call to `Put` to include a resource.
> Correcting a call to Put

- build/Build.cs
Copies `Octopus.Server.Client.nupkg` to `LocalPackages` folder for local development with `Octopus.Server`.
> Copy Octopus.Server.Client to LocalPackages

- .nuke/build.schema.json
- build/Build.cs
- build/_build.csproj
- source/OctopusClient.sln.DotSettings
So that the cert is loaded from azure key vault rather than disk
outstanding tasks:
> Use AzureSignTool for code signing

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/SpaceResource.cs
Related to work in [this pr](https://github.com/OctopusDeploy/OctopusDeploy/pull/11299)
> Add IsPrivate field to SpaceResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/FeedType.cs
- source/Octopus.Server.Client/Model/S3FeedResource.cs
- source/Octopus.Server.Client/Serialization/FeedConverter.cs
Adds new S3 Feed type to Client resources.
Related Server PR https://github.com/OctopusDeploy/OctopusDeploy/pull/11606
> Adds S3 feed type

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/SpaceResource.cs
Related to work in this [PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/11641)
> Add PrivateSpaceOwner to SpaceResource

- source/Octopus.Client.Tests/Repositories/ProjectRepositoryFixture.cs
- source/Octopus.Server.Client/Repositories/Async/ProjectRepository.cs
- source/Octopus.Server.Client/Repositories/ProjectRepository.cs
last PR had gotten rid of some changes I didn't intend to. this is part of work on https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/174
> reversing some inadvertent changes

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/IconResource.cs
- source/Octopus.Server.Client/Model/ProjectResource.cs
- source/Octopus.Server.Client/Model/SpaceResource.cs
- source/Octopus.Server.Client/Octopus.Server.Client.csproj
Add Icon Resource to Spaces and Projects. This is to enable persisting selected icons on the revamped icon picker
> Add IconResource changes

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client.Tests/Repositories/ProjectBetaRepositoryTests.cs
- source/Octopus.Client.Tests/Repositories/VariableSetBetaRepositoryTests.cs
- source/Octopus.Server.Client/Model/Git/ConvertProjectVariablesToGitCommand.cs
- source/Octopus.Server.Client/Model/Git/ConvertProjectVariablesToGitResponse.cs
- source/Octopus.Server.Client/Model/PersistenceSettings.cs
- source/Octopus.Server.Client/Repositories/Async/ProjectBetaRepository.cs
- source/Octopus.Server.Client/Repositories/Async/ProjectRepository.cs
- source/Octopus.Server.Client/Repositories/Async/VariableSetBetaRepository.cs
- source/Octopus.Server.Client/Repositories/Async/VariableSetRepository.cs
Adding Git variables support. It's still early days, and will be in a Beta repository. We may make breaking changes to this beta repository at any time.
Merge with: https://github.com/OctopusDeploy/OctopusDeploy/pull/12152
> Add Beta Project and VariableSet repositories

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Server.Client/Model/ReleaseTemplatePackage.cs
https://github.com/OctopusDeploy/OctopusDeploy/pull/12097#discussion_r875818663
> Add SelectedPackagePublished field to ReleaseTemplatePackage model

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/UserResource.cs
Related to this [PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/12437)
> Add Created field to UserResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/FeaturesConfigurationResource.cs
> add new jsm feature flag

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Server.Client/Model/ReleaseTemplatePackage.cs
This reverts commit c26f8d1ec813cb6bcb98faa73c6083edbf6398f8.
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/12910
> Revert "Add SelectedPackagePublished field to ReleaseTemplatePackage model (#655)"

- source/Octopus.Client.Tests/Model/InterruptionResourceFixture.cs
- source/Octopus.Client.Tests/Model/InterruptionTypeFixture.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/InterruptionResource.cs
- source/Octopus.Server.Client/Model/InterruptionType.cs
- source/Octopus.Server.Client/Serialization/InterruptionTypeConverter.cs
- source/Octopus.Server.Client/Serialization/JsonSerialization.cs
See https://github.com/OctopusDeploy/OctopusDeploy/pull/13027 for the server side PR
> Added `Interruption.Type`

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Permission.cs
Added Insights workspace permissions to match changes in https://github.com/OctopusDeploy/OctopusDeploy/pull/13358.
> Added Insights workspace permissions to match Server.

- .github/workflows/main.yaml
- source/Octopus.Server.Client/Octopus.Server.Client.csproj
This forms part of the .Net 6 upgrade project.  Octopus Clients both uses libraries that have been upgraded to remove support for .Net Framework 4.5.2 and is a library that needs to be upgraded to remove .Net Framework 4.5.2 so it can be used by key services. This PR is a "second pass" on the Octopus.Clients library to update its Octopus dependencies to versions that use the new versions.
The library should function as it did before, but now using .Net 6
Quality :heavy_check_mark:
🟢 build
- E.g. team/topic channels: [`#cloud-platform`](https://octopusdeploy.slack.com/archives/C01Q95KPRM4), [`#commercial-platform`](https://octopusdeploy.slack.com/archives/C06FUR5HN), [`#config-as-code`](https://octopusdeploy.slack.com/archives/C01AJE4K3T2), …
> Updated octopus dependencies to their Net 6 versions

- .github/workflows/main.yaml
> Removed testing code

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/LicenseStatusResource.cs
LicensedLimit -> the limit as written in the license
LicenseLimitDescription -> description of it
EffectiveLimit now takes into account an overrun if the license specifies it
> new properties on license status

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Endpoints/TentacleDetailsResource.cs
Add `bool UpgradeAvailable` to `TentacleDetailsResource`
Related to https://github.com/OctopusDeploy/OctopusDeploy/pull/13557
> Add upgradeAvailable to tentacleDetailsResource

- source/Octopus.Client.Tests/Extensions/DateTimeExtensionsFixture.cs
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Client.Tests/Serialization/CrossPlatformDateTimeZoneJsonConverterFixture.cs
- source/Octopus.Client.Tests/Serialization/PermissiveInstantJsonConverterFixture.cs
- source/Octopus.Server.Client/Extensions/DateTimeExtensions.cs
- source/Octopus.Server.Client/Octopus.Server.Client.csproj
- source/Octopus.Server.Client/Serialization/CrossPlatformDateTimeZoneJsonConverter.cs
- source/Octopus.Server.Client/Serialization/JsonSerialization.cs
- source/Octopus.Server.Client/Serialization/PermissiveInstantJsonConverter.cs
- Adds NodaTime support
- Serializers for `Instant` and `DateTimeZone`
> Add NodaTime support

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Git/ConvertProjectToGitCommand.cs
- source/Octopus.Server.Client/Model/PersistenceSettings.cs
- source/Octopus.Server.Client/Repositories/Async/ProjectRepository.cs
- source/Octopus.Server.Client/Repositories/ProjectRepository.cs
Adds a new optional field to GitPersistenceSettingsResource
> Add ProtectedDefaultBranch property to GitPersistenceSettingsResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/AzureContainerRegistryFeedResource.cs
- source/Octopus.Server.Client/Model/FeedType.cs
- source/Octopus.Server.Client/Model/GoogleContainerRegistry.cs
- source/Octopus.Server.Client/Serialization/FeedConverter.cs
Adding ACR & GCR feeds and feed types. [Slack thread](https://octopusdeploy.slack.com/archives/C020P7U9Z9S/p1667512890649209) for further details
> Adding ACR and GCR feeds

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Server.Client/Model/DeploymentSettingsResource.cs
- source/Octopus.Server.Client/Model/ProjectResource.cs
- source/Octopus.Server.Client/Model/RunbookResource.cs
Adding a ForcePackageDownload field for Runbooks & Project settings.
Related Server changes: https://github.com/OctopusDeploy/OctopusDeploy/pull/15914.
sc-30499
> Add ForcePackageDownload to Runbook, Project & ProjectSetting resources

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/EventResource.cs
> Add IpAddress to EventResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/ArchiveLimits/ArchiveLimitConfigurationResource.cs
Allow users to configure Archive Limit settings
> Adding ArchiveLimitConfigurationResource to the Octopus client

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Server.Client/Repositories/Async/DeploymentSettingsRepository.cs
To make them more consistent with other repositories.
> Add cancellation tokens for IDeploymentSettingsRepository

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Server.Client/Model/Endpoints/KubernetesAwsAuthenticationResource.cs
Adds properties for Azure EKS clusters to allow modifying/copying machines via client to include all necessary fields.
Fixes [OctopusClients/issues/738](https://github.com/OctopusDeploy/OctopusClients/issues/738)
[sc-45408]
These properties can now be updated when copying machines: 
```
Add-Type -Path 'C:\Users\isaac\.nuget\packages\octopus.client\14.3.546-isaac-aws-roles\lib\net462\Octopus.Client.dll'
$server = "http://localhost:8066/"
$apiKey = "API-key";              # Get this from your 'profile' page in the Octopus Web Portal
$endpoint = New-Object Octopus.Client.OctopusServerEndpoint($server, $apiKey)
$repository = New-Object Octopus.Client.OctopusRepository($endpoint)
$machine = $repository.Machines.Get("Machines-122");
Write-Host $machine;
Write-Host $machine.Name;
$machine.Name = …
```
> Adding AWS EKS additional props

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Server.Client/Model/DeploymentActionResource.cs
- source/Octopus.Server.Client/Model/GitDependencyResource.cs
- source/Octopus.Server.Client/Model/ReleaseResource.cs
- source/Octopus.Server.Client/Model/ReleaseTemplateGitResource.cs
- source/Octopus.Server.Client/Model/ReleaseTemplateResource.cs
- source/Octopus.Server.Client/Model/RunbookSnapshotResource.cs
- source/Octopus.Server.Client/Model/SelectedGitResource.cs
This PR adds client support for Git-sourced resources.  Is related to https://github.com/OctopusDeploy/OctopusDeploy/pull/19169 and a couple of others.
> Add support for Git-sourced resources

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/DeploymentActionContainerResource.cs
Related to https://github.com/OctopusDeploy/OctopusDeploy/pull/19857
> Add new properties used by inline execution containers

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Editors/Async/AzureOidcAccountEditor.cs
- source/Octopus.Server.Client/Editors/AzureOidcAccountEditor.cs
- source/Octopus.Server.Client/Extensions/TypeExtensions.cs
- source/Octopus.Server.Client/Model/Accounts/AccountType.cs
- source/Octopus.Server.Client/Model/Accounts/AzureOidcAccountResource.cs
- source/Octopus.Server.Client/Model/Accounts/AzureSubscriptionAccountResource.cs
- source/Octopus.Server.Client/Serialization/AccountConverter.cs
Adding Azure OIDC support. Need to think about merge timing.
[sc-57221]
> Azure OIDC

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/MachineRpcCallRetryPolicy.cs
Consolidate the 2 Health Check RPC Retry settings
Related Server PR https://github.com/OctopusDeploy/OctopusDeploy/pull/20361
> Consolidate the 2 Health Check RPC Retry settings

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/TaskResourceCollection.cs
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/20641
> Add TotalCountsInOtherSpaces to task resource collection

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/FeaturesConfigurationResource.cs
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/20877
> Added HelpSidebarSupportLinkLabel to FeatureConfigurationResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/ActionTemplateResource.cs
Adds client support for git sourced step templates - related to https://github.com/OctopusDeploy/OctopusDeploy/pull/21174
[sc-63602]
> Add git dependencies to ActionTemplateResource

- .github/workflows/main.yaml
Routine update of things that use GitHub actions to bring them up to the latest version
> Update GitHub actions dependencies

- .github/workflows/main.yaml
> Don't use PowerShell syntax in GitHub Action Bash scrippt

- .github/workflows/main.yaml
- build/Build.cs
- build/_build.csproj
- global.json
- source/Octopus.Client.E2ETests/Octopus.Client.E2ETests.csproj
- source/Octopus.Client.Tests/Integration/OctopusClient/TimeoutTests.cs
- source/Octopus.Client.Tests/Octopus.Client.Tests.csproj
> Use .NET 8 SDK

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/ActionTemplateSearchResource.cs
Related to this [PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/22456)
> Add IEnumerable<string> Features { get; set; } to ActionTemplateSearchResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/BuiltInTasks.cs
This is useful for our integration/e2e testing.
I deliberately left this off the "Canusers trigger this?" but love your thoughts.
> Add PollFeedsForTriggers to builtin tasks

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Triggers/FeedFilterResource.cs
Update client for changes made to the API model: https://github.com/OctopusDeploy/OctopusDeploy/pull/22888
> Add FeedCategory to FeedFilterResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/AuthenticationConfigResource.cs
Add Oidc Authentication Resource setting
> Isaac/authentication config OIDC issuer

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Endpoints/KubernetesTentacleEndpointResource.cs
- source/Octopus.Server.Client/Operations/IRegisterKubernetesClusterOperation.cs
- source/Octopus.Server.Client/Operations/RegisterKubernetesClusterOperation.cs
#project-k8s-agent
See https://github.com/OctopusDeploy/OctopusDeploy/pull/23271 for details
[sc-71237]
> Add default namespace property to Kubernetes Tentacle endpoint and register operation

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/LicenseUsageResource.cs
- source/Octopus.Server.Client/Model/SpaceLicenseUsageResource.cs
Add 2 new resources LicenseUsageResource and SpaceLicenseUsageResource to Octopus.Client
> Add LicenseUsageResource and SpaceLicenseUsageResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/LicenseStatusResource.cs
- source/Octopus.Server.Client/Model/LicenseUsageResource.cs
- source/Octopus.Server.Client/Model/TelemetryConfigurationResource.cs
- Add new LicenseLimitUsageResource class
- TelemetryConfigurationResource.IsTelemetryEnforced
> Update Client to match server change for PTM Licensing

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Triggers/FeedFilterResource.cs
Small change to move to deployment action slugs.
> Update client to match server change for Trigger action slug fix

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/MachineUpdatePolicy.cs
Connected to the changes coming in https://github.com/OctopusDeploy/OctopusDeploy/pull/24499
Shortcut story: [[sc-76174](https://app.shortcut.com/octopusdeploy/story/76174)]
> Add KubernetesAgentUpdateBehavior to MachineUpdatePolicy

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/TaskResource.cs
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/24637
> Add ProjectId to TaskResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/FeaturesConfigurationResource.cs
Adding a feature toggle for the prioritize task feature
Related to https://github.com/OctopusDeploy/OctopusDeploy/pull/25398
#project-fairer-task-queue
[sc-81062]
> Fairer Task Queue: Add isPrioritizeTaskEnabled to feature config

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/DeploymentResource.cs
- source/Octopus.Server.Client/Model/PriorityMode.cs
Changes priority from an enum to a string.
[sc-83222]
> Update priority to string

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/FeaturesConfigurationResource.cs
This reverts commit c0ee800dbc5fa711b7e2c19ec2b14ed60bd85e7c.
#project-fairer-task-queue
[sc-82630]
> Revert "Add prioritizeTaskEnabled to feature config (#853)"

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/ProjectResource.cs
Adding `ExecuteDeploymentsOnResilientPipeline` to `ProjectResource`
> Adding ResilientDeployment property to ProjectResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/ProjectResource.cs
This is to make the parameter optional
> Make ExecuteDeploymentsOnResilientPipeline nullable on ProjectResource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/TenantResource.cs
Adds the IsDisabled property to Tenant Resources required in https://github.com/OctopusDeploy/OctopusDeploy/pull/28737
> Add Tenant Isdisabled property

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Triggers/GitTriggers/GitFilterResource.cs
- source/Octopus.Server.Client/Model/Triggers/TriggerFilterResource.cs
- source/Octopus.Server.Client/Serialization/TriggerFilterConverter.cs
[sc-85541]
Add Git Repository Trigger
> Add Git Repository Trigger

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/DashboardTenantResource.cs
Adds the IsDisabled field to the tenant dashboard resource
> Add isDisabled to tenant dashboard resource

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/DeploymentResource.cs
- source/Octopus.Server.Client/Model/RunbookRunResource.cs
Related to https://github.com/OctopusDeploy/OctopusDeploy/pull/31942
> added priority to runbook run

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/BuiltInTasks.cs
Add runbook run to built in tasks as I need it for some tests
[sc-108097]
> Add built-in task for runbook run

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/S3FeedResource.cs
> Allow configuring region for s3 bucket feed

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/ProjectResource.cs
Adds `CombineHealthAndSyncStatusInDashboardLiveStatus` to `Project` for https://github.com/OctopusDeploy/OctopusDeploy/pull/33075
> Add CombineHealthAndSyncStatusInDashboardLiveStatus to Project

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/GetMissingPackagesForReleaseRequest.cs
- source/Octopus.Server.Client/Model/GetMissingPackagesForReleaseResponse.cs
- source/Octopus.Server.Client/Repositories/Async/ReleaseRepository.cs
- source/Octopus.Server.Client/Repositories/ReleaseRepository.cs
Updates client to support getting missing packages for a release.
[sc-110352] [sc-110783]
> Add missing packages for release

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Permission.cs
> Add platform hub permissions to client

- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETCore.approved.txt
- source/Octopus.Client.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress..NETFramework.approved.txt
- source/Octopus.Server.Client/Model/Permission.cs
> Add retention administer permission
